// Local seed used when Vercel Edge Config is not connected.
// Mirrors exactly what would live under the Edge Config `siteData` key.
// Shape is validated by SiteDataSchema at the boundary (config/store.js).

export const seed = {
  events: [
    // UPCOMING (validated against organizer posts, Jun 2026)
    { name: 'Pobla Matcha Fest', org: 'Souk Pop-up · @soukpopup + @omg_market.ph', tags: ['upcoming', 'star'], status: ['🌱 Upcoming', 'p-up'], star: true,
      theme: 'Matcha, tea & lifestyle street fest', date: 'Jul 11, 2026 (Sat PM) · ✓ verified', venue: 'The Fun Roof, Poblacion, Makati',
      size: 'Medium rooftop · ~40–60 booths', people: '~2,000–4,000 / day', vendor: { c: 'open', ic: '💚', t: 'Call OPEN — “looking for matcha merchants & cafés” (@omg_market.ph, Jun 15)' } },
    { name: 'Moonlit Market: Matcha Fest', org: 'Moonlit Market Events · @themoonlitevents', tags: ['upcoming', 'star'], status: ['🌱 Upcoming', 'p-up'], star: true,
      theme: 'Matcha night bazaar — food · fashion · finds', date: 'Jul 3–5, 2026 · 1–11 PM · ✓ verified', venue: 'Burgos Park, Forbestown, BGC',
      size: 'Large · 3-day · ~50–80 booths', people: '~5,000–10,000 / 3 days', vendor: { c: 'open', ic: '💚', t: 'Call OPEN — food & non-food (quick food, drinks, crafts)' } },
    { name: 'Pride & Matcha Fest', org: 'The Manila Market Club · @themanilamarketclub', tags: ['upcoming'], status: ['🎀 This week', 'p-soon'],
      theme: 'Pride × Matcha celebration · 12+ matcha booths', date: 'Jun 26–28, 2026 · ✓ verified', venue: 'Greenhills Mall, San Juan',
      size: 'Medium–large · ~40 booths', people: '~3,000–6,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Likely full (days away) — follow @themanilamarketclub for the next' } },
    { name: 'Moonlit Market (Aug)', org: 'Moonlit Market Events · @themoonlitevents', tags: ['upcoming'], status: ['🌱 Upcoming', 'p-up'],
      theme: 'Matcha / lifestyle night market', date: 'Aug 7–9, 2026 · ~ to confirm', venue: 'Assembly Grounds, The Rise, Makati',
      size: 'Large · 3-day', people: '~4,000–8,000 / 3 days', vendor: { c: 'wait', ic: '⏳', t: 'Organizer-listed — watch for the merchant call, DM @themoonlitevents' } },
    { name: 'The Merry Matcha Market', org: 'Holiday Makers & Art Bazaar', tags: ['upcoming'], status: ['🌱 Upcoming', 'p-up'],
      theme: 'Holiday matcha + makers & art bazaar', date: 'Dec 19, 2026 · 11–7 · ~ to confirm', venue: 'Gimenez Gallery',
      size: 'Small–medium gallery', people: '~500–1,500 (est.)', vendor: { c: 'open', ic: '💚', t: 'Call for merchants OPEN (seen once — reconfirm nearer date)' } },

    // RECURRING ORGANIZERS — pitch for their next edition
    { name: 'Matcha & Hojicha Collective', org: 'The Modern Market · @themodernmarket.ph', tags: ['recurring', 'star'], status: ['🔁 Recurring', 'p-rec'], star: true,
      theme: 'Curated matcha & hojicha café collective', date: '~Monthly · last Eastwood Jun 19–21', venue: 'Rotating malls (Eastwood · Uptown BGC · Alabang West Parade · Podium)',
      size: 'Large · mall-grade reach (32.6K followers)', people: 'Thousands / weekend', vendor: { c: 'open', ic: '💚', t: 'Onboard via Silk Events Mgt · @silkeventsmgt' } },
    { name: 'Souk Matcha Fest (series)', org: 'Souk Pop-up · @soukpopup', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha + tea + lifestyle, 60+ purveyors', date: '~Monthly editions thru 2026', venue: 'Glorietta · Trinoma · Eastwood · Poblacion',
      size: 'Large · 60+ vendors / run', people: 'Thousands / weekend (est.)', vendor: { c: 'open', ic: '💚', t: 'Recurring open calls — DM @soukpopup' } },
    { name: 'The Manila Market Club', org: '@themanilamarketclub', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha fests & themed markets (12+ booths)', date: 'Ran Nuvali (May) & Greenhills (Jun 26–28)', venue: 'Greenhills, San Juan · Nuvali · roving',
      size: 'Medium–large · 12+ matcha booths', people: '~3,000–6,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Active organizer — DM @themanilamarketclub for the next' } },
    { name: 'The Social Fair: Summer Matcha Fest', org: '@thesocialfair.ph', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Weekday matcha fair — food & non-food', date: 'Recurring · last merchant call Apr 2026', venue: 'Metro Manila (venue rotates)',
      size: 'Medium · weekday fair', people: '~1,000–2,500 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Opens merchant calls — follow @thesocialfair.ph' } },
    { name: 'Matcha & Makers Fest', org: 'Assembly Grounds · The Rise', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha × makers/creators community fest', date: 'Ran May 4–6 · watch for next', venue: 'Assembly Grounds, The Rise, Makati',
      size: 'Medium · creators market', people: '~2,000–4,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Creators market — watch Assembly Grounds for the next call' } },
    { name: 'Matcha Madness Bazaar', org: 'lyf Malate · bazaar org', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: '3-day matcha pop-up market', date: 'Ran Mar 25–27 · watch for next', venue: 'lyf Malate, Manila',
      size: 'Medium · 3-day pop-up', people: '~1,500–3,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Merchant applications open per edition — watch for next' } },
    { name: 'Mini Matcha Festival', org: 'Inside Marikina', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Cozy neighborhood matcha festival', date: 'Ran Jun 13–14 · watch for next', venue: 'Marikina',
      size: 'Small · neighborhood 2-day', people: '~800–2,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Brands & merchants gather — watch Inside Marikina' } },
    { name: 'Manila Matcha Fest', org: '@manilamatchafest', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha & hojicha festival (themed)', date: 'Recurring (e.g. “Love & Matcha”)', venue: 'SM Mall of Asia & others',
      size: 'Large · mall atrium', people: 'High mall foot traffic', vendor: { c: 'wait', ic: '⏳', t: 'Follow page for the next merchant call' } },
    { name: 'Matcha & Arts Fest', org: 'Wet Market PH · @wetmarketph', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha × art market crossover', date: 'Recurring (Feb–May editions)', venue: 'Metro Manila',
      size: 'Medium–large · ~15 shops + 40 artists', people: '~2,000–4,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Follow @wetmarketph for the next call' } },
    { name: 'Matcha Social', org: 'Cabana Club · Corner House', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Curated boutique matcha pop-up', date: 'Ran May 30–31 · watch for next', venue: 'Corner House, San Juan',
      size: 'Boutique · ~18 brands', people: '~1,000–2,500 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Track Cabana Club / Corner House' } },
    { name: 'Coffee & Matcha Collective', org: 'Pasig', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Coffee × matcha collective', date: 'Ran Mar 2026 · watch for next', venue: 'Pasig',
      size: 'Medium', people: '~1,500–3,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Track organizer for the next edition' } },
    { name: 'Matcha Mania', org: '3 Torre Lorenzo', tags: ['recurring'], status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha + indie art, student-area pop-up', date: 'Ran Feb 23–24 · watch for next', venue: '3 Torre Lorenzo (U-belt)',
      size: 'Medium · ~10 brands + 40 artists', people: '~2,000–3,500 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Follow for the next pop-up call' } },
  ],

  matchaOptions: [
    { l: 'Nokori · Komo everyday ceremonial (₱14/g)', g: 14 },
    { l: 'Matcha Moments · Miyu café blend (₱17.6/g)', g: 17.6 },
    { l: 'Naoki · Barista Blend (₱26/g)', g: 26 },
    { l: 'Ritual · Kasane ceremonial (₱31/g)', g: 31 },
    { l: 'Marukyu-Koyamaen · Aoarashi (₱33/g)', g: 33 },
    { l: 'Yamamasa Koyamaen · ceremonial (₱40/g)', g: 40 },
  ],
  milkOptions: [
    { l: 'Magnolia fresh dairy — ₱99/L', ml: 0.09925 },
    { l: 'Oatside oat · barista — ₱114/L', ml: 0.11425 },
    { l: 'Barista dairy — ~₱130/L', ml: 0.13 },
    { l: 'Evap/UHT budget — ~₱85/L', ml: 0.085 },
  ],
  pricing: { extras: 11 }, // cup + lid + ice + sugar, per 16oz cup
  drinks: [
    { name: 'Basic Matcha Latte', note: 'the everyday hero', flavor: '', milkMl: 180, fl: 0, srp: 150 },
    { name: 'Ichigo Matcha Latte', note: 'strawberry compote', flavor: '🍓 strawberry', milkMl: 180, fl: 14, srp: 180 },
    { name: 'Seasalt Matcha Latte', note: 'salted cream foam', flavor: '🧀 cream foam', milkMl: 180, fl: 15, srp: 180 },
    { name: 'Shoyu Matcha', note: 'umami-sweet novelty', flavor: '🍶 soy+caramel', milkMl: 180, fl: 5, srp: 160 },
    { name: 'Pistachio Matcha Latte', note: 'nutty pistachio', flavor: '🥜 pistachio', milkMl: 180, fl: 34, srp: 200 },
    { name: 'Sakura Matcha Latte', note: 'floral, seasonal', flavor: '🌸 sakura', milkMl: 180, fl: 36, srp: 200 },
    { name: 'Calamansi Matcha', note: 'citrus, light/no milk', flavor: '🍋 calamansi+honey', milkMl: 80, fl: 8, srp: 160 },
    { name: 'Iced Lychee Matcha', note: 'light & fruity', flavor: '🫧 lychee', milkMl: 80, fl: 28, srp: 180 },
    { name: 'Horchata Matcha', note: 'cinnamon-rice cream', flavor: '🥛 horchata', milkMl: 150, fl: 13, srp: 170 },
  ],
  ingredients: [
    { il: '🍵 Matcha · budget culinary', iv: 'Little Retail Pure Unsweetened — ₱180/100g (₱1.8/g)', url: 'https://littleretailph.com/products/pure-unsweetened-matcha-powder' },
    { il: '🍵 Matcha · latte grade', iv: 'JapanMatcha Latte Grade — ₱900/100g (₱9/g)', url: 'https://www.japanmatcha.ph/products/matcha-from-japan-ceremonial-and-culinary-grade-uji' },
    { il: '🍵 Matcha · premium ceremonial', iv: 'JapanMatcha Premium Ceremonial — ₱1,590/100g (₱15.9/g)', url: 'https://www.japanmatcha.ph/products/matcha-from-japan-ceremonial-and-culinary-grade-uji' },
    { il: '🥛 Milk · fresh dairy', iv: 'Magnolia Fresh Milk 1L — ₱99.25 (SM Markets)', url: 'https://smmarkets.ph/10123686-magnolia-fresh-milk-1l.html' },
    { il: '🌾 Milk · oat (barista)', iv: 'Oatside Barista Blend 1L — ₱114.25 (Landers)', url: 'https://www.landers.ph/dairy-chilled/oatside-barista-blend-oat-milk-1-l-145862-40293' },
    { il: '🍦 Cream · whipping', iv: 'Emborg Whipping Cream 1L — ~₱448 (Shopee)', url: 'https://shopee.ph/Emborg-UHT-Whipping-Cream-1L-i.144900856.5540159124' },
    { il: '🍯 Syrup · flavor (Monin)', iv: 'Monin 700ml — ~₱700–850 (imported)', url: 'https://manila-wine.com/manila-wine-others/monin' },
    { il: '🥤 Cup + dome lid · 16oz', iv: 'Packaging Lab — ₱5.50 + ₱2.00 / pc (100s)', url: 'https://packaginglabph.com/products/elegant-pet-plastic-cup' },
    { il: '🍋 Calamansi', iv: '₱80–120/kg (PSA / public market)', url: 'https://psa.gov.ph/statistics/price-situationer/selected-agri-commodities' },
    { il: '🍓 Strawberry', iv: '₱100–300/kg (Baguio market)', url: 'https://tribune.net.ph/2026/04/02/strawberry-prices-in-baguio-drop-as-tourist-numbers-fall' },
  ],

  powders: [
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', star: true, name: 'Ritual Matcha Co.', origin: '“Kasane” · 1st-harvest ceremonial · Shizuoka → PH · wholesale + private label',
      taste: 'Deep umami, delicate sweetness, low bitterness — holds up in milk. Built to SUPPLY cafés (1kg bulk + OEM).',
      price: '₱1,250 / 40g · ₱31/g (far less at 1kg)', serving: '~₱62 retail (much less wholesale)',
      hype: '“Trusted by 300+ PH cafés” — the B2B insider pick. Best path to protected margins.', buy: 'ritualmatcha.ph + wholesale form', url: 'https://ritualmatcha.ph' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', star: true, name: 'Matcha Moments', origin: '“Miyu” café blend · 2nd-harvest · Yame, Fukuoka',
      taste: 'Nutty, toasted almond + pecan, savory umami, low bitterness. Best quality-for-price latte base; 500g / 1kg.',
      price: '₱1,760 / 100g · ₱17.6/g', serving: '~₱35', hype: 'Approachable-premium with transparent cultivar/harvest sourcing.', buy: 'matchamoments.ph · Shopee', url: 'https://matchamoments.ph' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Maison Midori', origin: '“Tenshi” Samidori · premium single-cultivar ceremonial · Kyoto',
      taste: 'Creamy, earthy, balanced umami-sweetness, minimal astringency. DTC-only (no wholesale tier yet).',
      price: '₱990 / 40g · ₱24.75/g', serving: '~₱50', hype: '🔥 Most viral + press-covered PH brand of 2025–26 — the marketing magnet. Sells out fast.', buy: 'maisonmidori.com · IG/TikTok', url: 'https://maisonmidori.com' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', star: true, name: 'Nokori', origin: '“Komo” · latte-tuned everyday ceremonial blend · Uji, Kyoto',
      taste: 'Mild, creamy, soft pistachio, custard-like, low astringency — designed not to fight the milk.',
      price: 'from ₱839 / 60g · ₱14/g', serving: '~₱28 (best boutique margin)', hype: 'Strong TikTok presence; the everyday-latte favorite. Small-batch drops sell out.', buy: 'nokorimatcha.com · Lazada', url: 'https://nokorimatcha.com' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Sobamatsu', origin: 'budget latte-oriented · Japan-sourced',
      taste: 'Light, grassy, latte-leaning — a cheap everyday option for high-volume value pricing.',
      price: '~₱600 / 50g · ₱12/g', serving: '~₱24', hype: 'Strong viral TikTok buzz as the affordable everyday pick.', buy: 'Shopee / Lazada', url: 'https://shopee.ph/search?keyword=sobamatsu%20matcha' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Little Retail PH', origin: 'Pure Unsweetened · culinary + ceremonial grades · QC, PH (Japan region unspecified)',
      taste: 'No-frills unsweetened powder you sweeten yourself — the budget workhorse for high-volume value lattes.',
      price: 'Culinary 100g ₱180 · ₱1.8/g · 1kg ₱1,188 (₱1.19/g) · Ceremonial 100g ₱3.25/g', serving: '~₱2.4–3.6 / 2g (culinary)',
      hype: 'The cheapest credible ₱/g in PH; ranked #3 in my-best\'s 2026 PH matcha guide.', buy: 'littleretailph.com · Lazada · Shopee', url: 'https://littleretailph.com/products/pure-unsweetened-matcha-powder' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Matcha Mill', origin: 'single-origin by prefecture (Kirishima/Uji/Yame/Shizuoka) · PH\'s first local stone-miller · Davao',
      taste: 'Single-origin Kirishima: nutty/creamy — almond, pistachio, avocado, heavy creamy body, low-moderate bitterness.',
      price: 'Single-origin 100g ₱840 · ₱8.4/g · 1kg ₱7,392 (₱7.4/g) · organic up to ₱24/g', serving: '~₱16.8 / 2g (single-origin)',
      hype: 'Niche serious-hobbyist favorite — the only PH brand milling fresh leaf locally (“fresher than imported tins”).', buy: 'matcha-mill.com (free ship ₱1,999+)', url: 'https://matcha-mill.com/products/kirishima-kagoshima-matcha' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Moonbug Matcha', origin: '“OG” Shizuoka ceremonial blend · JAS + USDA organic · Shizuoka/Kagoshima/Uji/Yame',
      taste: 'Smooth, creamy, grassy with mild nutty umami + bright astringency. Polarizing — some find it “too grassy” unsweetened.',
      price: '30g ₱700 · ₱23.3/g · 100g ₱1,900 (₱19/g)', serving: '~₱38–47 / 2g',
      hype: 'Buzzy organic daily-driver (~4.5/5 on matcha TikTok); the certified-organic value pick.', buy: 'moonbugmatcha.com · Lazada · Shopee', url: 'https://moonbugmatcha.com/products/authentic-ceremonial-matcha' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Made in Matcha', origin: '“Everyday” blend / “Ukiyo” single-origin · Kagoshima (Yabukita) · locally stone-milled “farm-to-cup”',
      taste: 'Everyday: balanced, grassy, light umami, gentle bitterness. Ukiyo: smooth, umami-rich, creamy, subtly sweet.',
      price: 'Everyday 30g ₱950 · ₱31.7/g · Ukiyo single-origin 30g ₱1,800 (₱60/g)', serving: '~₱63 / 2g (Everyday) · ~₱120 (Ukiyo)',
      hype: 'Buzzy Filipino “farm-to-cup” brand — Kagoshima leaf stone-ground locally, sold on cultivar transparency.', buy: 'madeinmatcha.com', url: 'https://madeinmatcha.com/products/everyday-matcha-30g-blend' },
    { cat: 'jp', catlabel: '🇯🇵 Japanese · in PH', star: true, name: 'Yamamasa Koyamaen', origin: '“Matsukaze / Ogurayama” · ceremonial · Uji, Kyoto (est. 1704)',
      taste: 'Ogurayama: creamy, velvety, umami + sweet, floral-nutty. Matsukaze: vegetal, light, holds color in milk.',
      price: '30g cans ~₱800–2,100 · ₱27–70/g', serving: '~₱53 – ₱93', hype: 'Very high on TikTok, near Ippodo tier — in stock at Midori PH, sells out fast.', buy: 'Midori Matcha PH · japanmatcha.ph', url: 'https://midorimatchaph.com/collections/yamamasa-koyamaen' },
    { cat: 'jp', catlabel: '🇯🇵 Japanese · in PH', name: 'The Matcha Tokyo', origin: '“Tokyo Rich / Japan Premium” · 100% organic · Kagoshima/Uji leaf',
      taste: 'Bold umami, low astringency, grassy, rich bitter finish. Tokyo Rich is latte-optimized.',
      price: 'Tokyo Rich ₱1,540/20g (₱77/g)', serving: '~₱154–220 (retail — negotiate B2B)', hype: 'High — viral on TikTok, top Manila matcha; 13+ PH cafés.', buy: 'PH cafés · GrabFood · order site', url: 'https://thematchatokyo-ph.tablevibe.co/' },
    { cat: 'jp', catlabel: '🇯🇵 Japanese · in PH', name: 'Tsujiri', origin: '“Ume No Shiro” ceremonial · Uji, Kyoto heritage (est. 1860) · tins sold in-store at PH cafés',
      taste: 'Smooth, creamy ceremonial Uji with balanced sweetness-to-bitterness — the “beginner\'s ceremonial,” vegetal-forward, mild umami.',
      price: '30g / 100g tins · ≈ ₱48/g (est. from import; no confirmed PH online price)', serving: '~₱97 / 2g (est.)',
      hype: '160-yr Uji-Kyoto matcha dynasty — soft-serve queues & ceremonial tins from one heritage. Ask in-store for tins.', buy: 'TSUJIRI PH cafés (Podium, SM Aura, Greenbelt 5…) · FB tsujiri.ph', url: 'https://www.facebook.com/tsujiri.ph/' },
    { cat: 'jp', catlabel: '🇯🇵 Japanese · in PH', name: 'Ito En', origin: 'Japan\'s #1 green-tea brand (Shizuoka, 1966) · mass-market · PH shelf SKU = sweetened matcha-latte mix',
      taste: 'Sweet Matcha: mellow, sweet, lightly grassy — a ready-to-mix latte flavor (sugar-added), NOT a bitter ceremonial whisk.',
      price: 'Sweet Matcha mix 120g ≈ ₱730 · ₱6/g (sweetened) · pure culinary ~₱11.6/g (not stocked in PH)', serving: '~₱12 / 2g (sweetened mix)',
      hype: 'The easy supermarket “matcha latte” grab — cheap & everywhere, but a sweetened mix, not pure matcha (verify live PHP price).', buy: 'Lazada PH (official store) · Shopee · SM / Landers', url: 'https://www.lazada.com.ph/ito-en/' },
    { cat: 'import', catlabel: '🌏 Imported', star: true, name: 'Marukyu-Koyamaen', origin: '“Aoarashi” (hero) / “Wakatake” (bulk) · Uji, Kyoto (est. ~1704)',
      taste: 'Aoarashi: brisk, bold, grassy, vibrant green — a ceremonial that SURVIVES milk. Wakatake = culinary bulk.',
      price: 'PH ₱1,300 / 40g · ₱33/g', serving: '~₱40–65', hype: 'Prestige tea-ceremony supplier; Aoarashi is the PH cult-favorite. Chronic sellouts.', buy: 'Midori Matcha PH · Japan Matcha PH', url: 'https://midorimatchaph.com/collections/marukyu-koyamaen' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Ippodo', origin: '“Ikuyo” (latte) / “Sayaka” (premium) · Uji/Kyoto (est. 1717)',
      taste: 'Ikuyo: balanced, mild umami, snappy, nutty/white-chocolate, photogenic green. The prestige benchmark.',
      price: 'PH café 100g ₱3,000 · ₱30/g', serving: '~₱60 (₱90 at 3g)', hype: 'Top benchmark; won\'t ship to PH direct — buy via resellers. Shortage + sellouts.', buy: 'MODO @ Mitsukoshi BGC · Matcha Tana', url: 'https://modo.ph/collections/ippodo-tea' },
    { cat: 'import', catlabel: '🌏 Imported', star: true, name: 'Naoki Matcha', origin: '“Barista Blend” · latte/barista grade · Kagoshima + Uji leaf',
      taste: 'Bold, earthy, roasty — built to cut through milk. Great-value café-quality; B2B program available.',
      price: '40g ≈ ₱1,025 · ₱26/g (culinary ~₱8.5/g)', serving: '~₱52', hype: 'Loved on TikTok/Lemon8 as best-value café-quality; gripe: duller color.', buy: 'Shopee PH · direct import · B2B', url: 'https://naokimatcha.com/products/barista-blend-matcha' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Encha', origin: '“Latte / Barista Grade” · organic single-origin Uji',
      taste: 'Latte Grade: bold, cuts through milk. Barista: nutty, toasted, chocolate. Best value in 500g bulk.',
      price: 'Latte 500g ₱17/g · Barista 500g ₱11/g', serving: 'Latte ~₱34 · Barista ~₱22', hype: 'Popular organic/value pick — import-only, and a 2025 heavy-metals flag worth knowing.', buy: 'Import-only · Lazada cross-border', url: 'https://encha.com/collections/all' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Aiya', origin: '“Culinary” (Ceremonial for premium) · Nishio, Aichi (since 1888)',
      taste: 'Culinary: bolder, mildly astringent, strong enough for milk. World\'s largest producer — café bulk workhorse.',
      price: 'Culinary 100g ₱18/g · 1kg ~₱9.7/g', serving: '~₱19–20 (bulk culinary)', hype: 'Reliable café workhorse; enthusiasts rate ceremonial “mid”. No confirmed PH distributor.', buy: 'Import via Aiya America / wholesale', url: 'https://aiya-america.com/retail/matcha-products/' },
    { cat: 'import', catlabel: '🌏 Imported', name: "Rocky's Matcha", origin: 'ceremonial blends + single cultivars · US brand, Japanese leaf (Yame/Uji)',
      taste: 'Smooth, creamy, nutty, natural sweetness, low bitterness. A TikTok cult darling.',
      price: '₱2,088 / 20g (US$36) · ₱104/g · 100g ≈ ₱45/g', serving: '~₱209 / 2g flagship · ~₱90 at 100g', hype: 'Huge on TikTok but pricey & import-only — sole PH reseller (Glow PH) is out of stock; buy direct via DHL.', buy: 'rockysmatcha.com (DHL import) · Glow PH (OOS)', url: 'https://www.rockysmatcha.com/products/rockys-matcha-ceremonial-blend-matcha-20g' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Jade Leaf', origin: 'Barista Edition / Teahouse · organic first-harvest · US brand, Uji + Kagoshima leaf',
      taste: 'Smooth, mild nuttiness + umami, made to cut through milk — an affordable, consistent gateway latte matcha.',
      price: 'Barista 50g ₱1,698 (₱34/g) · 1lb bulk ₱24.4/g · ceremonial 30g ₱50/g', serving: '~₱50–70 / 2g (Barista)',
      hype: 'Top US-market organic “gateway” brand — affordable & consistent, not a connoisseur single-origin.', buy: 'Ubuy PH (cross-border import) · jadeleafmatcha.com', url: 'https://www.ubuy.com.ph/brand/jade-leaf-matcha' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Hibiki-an', origin: 'single-estate Uji, Kyoto · direct-from-Japan grower · Superior → Premium → Super Premium → Pinnacle',
      taste: 'Super Premium: bright, thick, umami-rich, koicha-capable ceremonial. Superior = everyday usucha entry; Pinnacle = smoothest flagship.',
      price: '₱30–90/g across grades · Super Premium 40g US$39 (₱59.5/g) · 120g refill ₱49.8/g', serving: '~₱61–119 / 2g',
      hype: 'Cult Uji grower selling genuine farm-direct ceremonial — real Kyoto leaf without a middleman.', buy: 'hibiki-an.com (ships to PH, direct import + duties)', url: 'https://www.hibiki-an.com/sp/product_info.php/products_id/349' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Nakamura Tokichi', origin: 'historic Uji tea house (est. 1854) · usucha → flagship koicha · Uji, Kyoto',
      taste: 'Fuji-no-Shiro: delicate bitterness, balanced astringency, clean light finish — versatile for usucha or lattes.',
      price: 'Fuji-no-Shiro 30g ¥2,000 ≈ ₱26/g · Standard 100g ₱46.8/g · flagship Uji-no-Mukashi ₱117/g', serving: '~₱52 / 2g (entry) · ~₱234 (flagship)',
      hype: '170-year-old Uji institution — authentic ceremonial Kyoto matcha shipped straight from the source.', buy: 'global.tokichi.jp (ships to PH via DHL + duties)', url: 'https://global.tokichi.jp/products/mc2' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Hoshinoen (Yame no Hana)', origin: 'premium Yame, Fukuoka (Hoshino Seichaen) · ceremonial Okumidori · TikTok-viral',
      taste: 'Smooth, nutty-toasted, lightly smoky, subtly sweet with almost no bitterness — creamy in lattes; rated ~10/10 for the price.',
      price: '30g ¥2,500 ≈ ₱32.5/g (origin) · ~₱45–60/g landed after forwarder', serving: '~₱65 / 2g (origin) · ~₱90–120 landed',
      hype: 'TikTok-viral Yame matcha (“10/10 for the price”) — but import/forwarder-only & almost always SOLD OUT.', buy: 'Wakokoro Tea (ships from Japan) · forwarder — no PH reseller', url: 'https://wakokoro-tea.com/products/matcha-yame-no-hana-by-hoshino-seichaen-40g' },
  ],

  // product photos (validated, hotlinkable) — brands not listed fall back to a colour dot
  powderImages: {
    'Ritual Matcha Co.': 'https://ritualmatcha.ph/cdn/shop/files/82C527CD-8412-417F-A044-C8B35484610D-m.jpg?v=1765003806&width=1080',
    'Matcha Moments': 'https://matchamoments.ph/cdn/shop/files/MatchaJar40g.png?v=1774959728&width=1080',
    'Maison Midori': 'https://cdn.shopify.com/s/files/1/0722/4947/5290/files/IMG_0362.jpg?v=1771896071',
    'Yamamasa Koyamaen': 'https://cdn.shopify.com/s/files/1/0670/1930/9219/files/Rebranded_-_Yamamasa.png?v=1777053923',
    'The Matcha Tokyo': 'https://images.tablevibestaticassets.co/52x2a58ziio06i2yg0d6nwlldn2q',
    'Marukyu-Koyamaen': 'https://cdn.shopify.com/s/files/1/0670/1930/9219/files/13.png?v=1777047613',
    'Ippodo': 'https://cdn.shopify.com/s/files/1/0685/8732/3548/files/Gokujo-Hojicha---100g.jpg?v=1754985762',
    'Naoki Matcha': 'https://cdn.shopify.com/s/files/1/0860/9716/6639/files/AMZPL_1_barista-blend-hero-40g.jpg?v=1752807321',
    'Encha': 'https://cdn.shopify.com/s/files/1/0668/5149/files/Latte60g.jpg?v=1766371283',
    'Aiya': 'https://cdn11.bigcommerce.com/s-30z03xaf7j/images/stencil/1280x1280/products/1774/3095/ceremonial-matcha-tin-30g__80403.1781628290.jpg?c=1',
    "Rocky's Matcha": 'https://cdn.shopify.com/s/files/1/0689/8037/5866/files/EDITED100G-29Rocky_sMatchaFeb2024-2-updated.jpg?v=1742012604',
  },
};
