// Canonical content seed — the single source of truth read by config/store.js.
// Shape is validated by SiteDataSchema at the boundary (config/store.js).

export const seed = {
  events: [
    // UPCOMING (validated against organizer posts, Jun 2026)
    { name: 'Pobla Matcha Fest', org: 'OMG! Market · @omg_market.ph', status: ['🌱 Upcoming', 'p-up'], start: '2026-07-11',
      theme: 'Matcha, tea & lifestyle street fest', date: 'Jul 11, 2026 (Sat PM) · ✓ verified', venue: 'The Fun Roof, Poblacion, Makati',
      size: 'Medium rooftop · ~40–60 booths', people: '~2,000–4,000 / day', vendor: { c: 'open', ic: '💚', t: 'Call OPEN — “looking for matcha merchants & cafés” (@omg_market.ph, Jun 15)' } },
    { name: 'Moonlit Market: Matcha Fest', org: 'Moonlit Market Events · @themoonlitevents', status: ['🌱 Upcoming', 'p-up'], start: '2026-07-03',
      theme: 'Matcha night bazaar — food · fashion · finds', date: 'Jul 3–5, 2026 · 1–11 PM · ✓ verified', venue: 'Burgos Park, Forbestown, BGC',
      size: 'Large · 3-day · ~50–80 booths', people: '~5,000–10,000 / 3 days', vendor: { c: 'open', ic: '💚', t: 'Call OPEN — food & non-food (quick food, drinks, crafts)' } },
    { name: 'Pride & Matcha Fest', org: 'The Manila Market Club · @themanilamarketclub', status: ['🌱 Upcoming', 'p-up'], start: '2026-06-26',
      theme: 'Pride × Matcha celebration · 12+ matcha booths', date: 'Jun 26–28, 2026 · ✓ verified', venue: 'Greenhills Mall, San Juan',
      size: 'Medium–large · ~40 booths', people: '~3,000–6,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Likely full (days away) — follow @themanilamarketclub for the next' } },
    { name: 'Moonlit Market (Aug)', org: 'Moonlit Market Events · @themoonlitevents', status: ['🌱 Upcoming', 'p-up'], start: '2026-08-07',
      theme: 'Matcha / lifestyle night market', date: 'Aug 7–9 · ✓ IG-confirmed (@themoonlitevents)', venue: 'Assembly Grounds, The Rise, Makati',
      size: 'Large · 3-day', people: '~4,000–8,000 / 3 days', vendor: { c: 'wait', ic: '⏳', t: 'Organizer-listed — watch for the merchant call, DM @themoonlitevents' } },
    { name: 'The Merry Matcha Market', org: 'Holiday Makers & Art Bazaar', status: ['🌱 Upcoming', 'p-up'], start: '2026-12-19',
      theme: 'Holiday matcha + makers & art bazaar', date: 'Dec 19, 2026 · 11–7 · ~ to confirm', venue: 'Gimenez Gallery',
      size: 'Small–medium gallery', people: '~500–1,500 (est.)', vendor: { c: 'open', ic: '💚', t: 'Call for merchants OPEN (seen once — reconfirm nearer date)' } },
    { name: 'Souk @ Greenhills', org: 'Souk Pop-up · @soukpopup', status: ['🌱 Upcoming', 'p-up'], start: '2026-07-01',
      theme: 'Souk market run (PH’s top matcha-fest organizer)', date: 'Jul 1–5 · ✓ per @soukpopup IG bio', venue: 'Greenhills, San Juan',
      size: 'Large · Souk-scale', people: 'Thousands / run (est.)', vendor: { c: 'open', ic: '💚', t: 'Souk runs the matcha fests — sign-up link in @soukpopup bio' } },
    { name: 'Manila Market Club (Aug editions)', org: 'The Manila Market Club · @themanilamarketclub', status: ['🌱 Upcoming', 'p-up'], start: '2026-08-08',
      theme: 'Themed markets by the Pride & Matcha Fest organizer', date: 'Aug 8–9 & Aug 21–23 · ✓ per IG (venues TBA)', venue: 'Metro Manila · TBA',
      size: 'Medium–large · matcha-fest organizer', people: '~3,000–6,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Two Aug editions listed (venues TBA) — DM @themanilamarketclub for booths' } },

    // RECURRING ORGANIZERS — pitch for their next edition
    { name: 'Matcha & Hojicha Collective', org: 'The Modern Market · @themodernmarket.ph', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Curated matcha & hojicha café collective', date: 'Recurring · last Jun 26–28 (Rizal Row, Estancia) · DM for July', venue: 'Rotating Megaworld malls (Estancia · Eastwood · Uptown BGC · Podium)',
      size: 'Large · mall-grade reach (32.6K followers)', people: 'Thousands / weekend', vendor: { c: 'open', ic: '💚', t: 'Onboard via Silk Events Mgt · @silkeventsmgt' } },
    { name: 'Souk Matcha Fest (series)', org: 'Souk Pop-up · @soukpopup', status: ['🔁 Recurring', 'p-rec'], start: '2026-07-03',
      theme: 'Matcha + tea + lifestyle, 60+ purveyors', date: 'Next Jul 3–5, 2026 · Nuvali (Solenad)', venue: 'Ayala Malls Nuvali (Solenad) · then rotates',
      size: 'Large · 60+ vendors / run', people: 'Thousands / weekend (est.)', vendor: { c: 'open', ic: '💚', t: 'Recurring open calls — DM @soukpopup' } },
    { name: 'The Manila Market Club', org: '@themanilamarketclub', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha fests & themed markets (12+ booths)', date: 'Ran Nuvali (May) & Greenhills (Jun 26–28)', venue: 'Greenhills, San Juan · Nuvali · roving',
      size: 'Medium–large · 12+ matcha booths', people: '~3,000–6,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Active organizer — DM @themanilamarketclub for the next' } },
    { name: 'The Social Fair', org: 'The Social Fair · @thesocialfair.ph', status: ['🔁 Recurring', 'p-rec'], start: '2026-07-17',
      theme: 'Lifestyle market — food & non-food (ran the Summer Matcha Fest)', date: 'Next Jul 17–19 · Somerset Alabang (+ Jul 24–26 TBA)', venue: 'Somerset Alabang, Manila (rotates)',
      size: 'Medium · weekend fair', people: '~1,000–2,500 (est.)', vendor: { c: 'open', ic: '💚', t: 'Merchant calls via @thesocialfair.merchants — Jul 17–19 Somerset Alabang' } },
    { name: 'Matcha & Makers Fest', org: 'Assembly Grounds · The Rise', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha × makers/creators community fest', date: 'Ran May 4–6 · watch for next', venue: 'Assembly Grounds, The Rise, Makati',
      size: 'Medium · creators market', people: '~2,000–4,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Creators market — watch Assembly Grounds for the next call' } },
    { name: 'Mini Matcha Festival', org: 'Inside Marikina', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Cozy neighborhood matcha festival', date: 'Ran Jun 13–14 · watch for next', venue: 'Marikina',
      size: 'Small · neighborhood 2-day', people: '~800–2,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Brands & merchants gather — watch Inside Marikina' } },
    { name: 'Manila Matcha Fest', org: 'Manila Matcha Fest · @matchafestph', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha & hojicha festival (themed)', date: 'Recurring · annual (~late Aug); next TBA', venue: 'SM Mall of Asia & others',
      size: 'Large · mall atrium', people: 'High mall foot traffic', vendor: { c: 'wait', ic: '⏳', t: 'Follow page for the next merchant call' } },
    { name: 'Matcha & Arts Fest', org: 'Wet Market: Art Market · @wetmarketph', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Matcha × art market crossover (incl. the “Matcha Mania” edition)', date: 'Recurring · next TBA (ran 3 Torre Lorenzo Feb 23–24)', venue: 'Roving (e.g. 3 Torre Lorenzo, Malate)',
      size: 'Medium–large · ~15 shops + 40 artists', people: '~2,000–4,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Apply: bit.ly/WetMarket-MerchantApplication' } },
    { name: 'Matcha Social', org: 'Cabana Club · Corner House', status: ['🔁 Recurring', 'p-rec'], start: '2026-07-09',
      theme: 'Boutique matcha pop-up · now touring w/ Brew & Whisk Club', date: 'Next Jul 9–12, 2026 · Brew & Whisk Club', venue: 'Ayala Malls Fairview Terraces, QC',
      size: 'Boutique · ~18 brands', people: '~1,000–2,500 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Track Cabana Club / Corner House' } },
    // SMALL / ARTY POP-UPS — great matcha-booth fits (recurring; watch for the Jul/Aug edition)
    { name: 'Palengke Club', org: 'Palengke Club · @palengkeclub', status: ['🌱 Upcoming', 'p-up'], start: '2026-08-03',
      theme: 'Community thrift + makers pop-up (matcha-friendly)', date: 'Aug 3–4, 2026 · ✓ Nhue Creative Studios', venue: 'Nhue Creative Studios, Makati',
      size: 'Small–medium · curated indie', people: '~800–2,000 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Hosts matcha booths (Chotto Matcha precedent) — DM @palengkeclub for a slot' } },
    { name: 'The Fig Archives', org: 'The Fig Archives · @thefigarchives', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Vintage + antiques rooftop market (arty)', date: 'Recurring · merchant form open now', venue: 'Legaspi Village, Makati (rooftop)',
      size: 'Small · boutique rooftop', people: '~500–1,500 (est.)', vendor: { c: 'open', ic: '💚', t: 'Merchant Interest Form OPEN — link in @thefigarchives IG bio' } },
    { name: 'The Solana Market', org: 'The Solana Market · @thesolanamarket', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Curated lifestyle market — 30+ merchants incl. food', date: 'Recurring · next edition “coming soon” (verified IG)', venue: 'Makati · Katipunan (rotating)',
      size: 'Medium–large · 30+ merchants, food vendors', people: 'Large reach · 30K+ IG following', vendor: { c: 'wait', ic: '⏳', t: 'Takes food/drink vendors — apply via linktr.ee/thesolanamarket' } },
    { name: 'The Merkado', org: 'The Merkado · @the.merkado', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Local + vintage brands pop-up market', date: 'Recurring · “see you at our next” (verified IG)', venue: 'Corner House, San Juan',
      size: 'Medium · local + vintage', people: 'Large reach · 29K+ IG following', vendor: { c: 'wait', ic: '⏳', t: 'Local + vintage + F&B — DM @the.merkado for vendor slots' } },
    { name: 'BGC Art Mart', org: 'Arts at BGC · @artsatbgc', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Art & makers market at BGC Arts Center', date: 'Select weekends · watch for next', venue: 'BGC Arts Center, Bonifacio Global City',
      size: 'Medium · artists + makers', people: 'High foot traffic', vendor: { c: 'wait', ic: '⏳', t: 'Public art program (BAFI) — not a standard F&B-vendor market; watch @artsatbgc' } },
    { name: 'The Crafters Marketplace', org: 'TCM · @thecraftersmarketplacemanila', status: ['🔁 Recurring', 'p-rec'],
      theme: 'Craft & makers market', date: 'Recurring · watch for next', venue: 'Cubao Expo, Quezon City',
      size: 'Small–medium · crafts', people: '~1,000–2,500 (est.)', vendor: { c: 'wait', ic: '⏳', t: 'Crafts + indie F&B — DM @thecraftersmarketplacemanila' } },

    // — Added Jun 2026 (research): August-focused + open-registration leads —
    { name: 'Patrons of the Arts: Magic Academy', org: 'Patrons of the Arts · @patronsofthearts', status: ['🔁 Recurring', 'p-rec'], start: '2026-08-01',
      theme: 'Huge indie art market — stickers, prints, zines, anik-anik', date: 'Aug 1–2, 2026 · Centris (per reg form)', venue: 'Centris Elements, Quezon City',
      size: 'Very large · ~390 artists', people: 'High · young art crowd', vendor: { c: 'open', ic: '💚', t: 'Artist form live — email marketing@patronsoftheartsph.com for a drinks/F&B booth' } },
    { name: 'ArteFino', org: 'ArteFino · @artefinoph', status: ['🌱 Upcoming', 'p-up'], start: '2026-08-30',
      theme: 'Premier Filipino artisan fair — has a food & drink hall', date: 'Aug 30–Sep 2, 2026 (verify)', venue: '8 Rockwell · Power Plant Mall, Makati',
      size: 'Large · 150+ Filipino brands', people: 'Large · upscale mall crowd', vendor: { c: 'open', ic: '💚', t: 'Curated fair with a food hall — apply early via artefinoph.com (selection screened)' } },
    { name: 'Katutubo Pop-Up Market', org: 'Katutubo Pop-Up · @katutubopopupmarket', status: ['🔁 Recurring', 'p-rec'], start: '2026-07-03',
      theme: 'Proudly-Filipino maker market — ~9 curated food stalls', date: 'Jul 3–5, 2026 · ✓ Bench Tower BGC', venue: 'Bench Tower, BGC, Taguig',
      size: 'Medium · ~60 makers + ~9 food', people: 'Strong BGC foot traffic', vendor: { c: 'wait', ic: '⏳', t: 'Curated food stalls — DM @katutubopopupmarket; pitch a local-matcha angle' } },
    { name: 'Mercato Centrale', org: 'Mercato Centrale · @mercatocentraleph', status: ['🔁 Recurring', 'p-rec'], start: '2026-06-27',
      theme: 'Weekend gourmet night food market — open vendor form', date: 'Every weekend · register anytime', venue: 'BGC (Taguig) & Ortigas Center',
      size: 'Large · dozens of F&B booths', people: 'Tens of thousands / weekend', vendor: { c: 'open', ic: '💚', t: 'F&B vendor form OPEN — mercatocentrale.ph/join-the-food-movement' } },
    { name: 'Global Pinoy Alabang Fair', org: 'Yabang Pinoy', status: ['🌱 Upcoming', 'p-up'], start: '2026-08-28',
      theme: 'Community marketplace — local finds + food booths', date: 'Aug 28–31, 2026 · ✓ reg open', venue: 'Alabang Town Center, Muntinlupa',
      size: 'Mall activity-center bazaar', people: 'Mall foot traffic', vendor: { c: 'open', ic: '💚', t: 'Registration OPEN — bit.ly/GPAlabangFair2026 (confirm a brewed-drinks booth is allowed)' } },
  ],

  // Human-navigable source links per event (keyed by name). Organizer IG handles
  // were verified live; venues link to Google Maps; a few use a web search.
  eventLinks: {
    'Patrons of the Arts: Magic Academy': [
      { kind: 'apply', url: 'https://docs.google.com/forms/d/e/1FAIpQLScUgM500-AoWuORbZ1gJ2pgXZC7T12rNd-Rto83EvNd2mhWqQ/viewform' },
      { kind: 'ig', url: 'https://www.instagram.com/patronsofthearts/' },
      { kind: 'web', url: 'https://patronsofthearts.carrd.co/' },
    ],
    'ArteFino': [
      { kind: 'apply', url: 'https://drive.google.com/file/d/1c6LQ2rsyzXmjpT1lBGgVTx0PmyHUYxGZ/view' },
      { kind: 'web', url: 'https://artefinoph.com/' },
      { kind: 'ig', url: 'https://www.instagram.com/artefinoph/' },
    ],
    'Katutubo Pop-Up Market': [
      { kind: 'ig', url: 'https://www.instagram.com/katutubopopupmarket/' },
      { kind: 'fb', url: 'https://www.facebook.com/katutubopopup' },
    ],
    'Mercato Centrale': [
      { kind: 'apply', url: 'https://mercatocentrale.ph/join-the-food-movement/' },
      { kind: 'ig', url: 'https://www.instagram.com/mercatocentraleph/' },
      { kind: 'web', url: 'https://mercatocentrale.ph/' },
    ],
    'Global Pinoy Alabang Fair': [
      { kind: 'apply', url: 'https://bit.ly/GPAlabangFair2026' },
      { kind: 'web', url: 'https://www.manilashopper.com/p/bazaar-expo-list.html' },
    ],
    'Pobla Matcha Fest': [
      { kind: 'ig', url: 'https://www.instagram.com/omg_market.ph/' },
      { kind: 'ig', url: 'https://www.instagram.com/the_funroof/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=The+Fun+Roof+Poblacion+Makati' },
    ],
    'Moonlit Market: Matcha Fest': [
      { kind: 'ig', url: 'https://www.instagram.com/themoonlitevents/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Burgos+Park+Forbestown+BGC+Taguig' },
    ],
    'Pride & Matcha Fest': [
      { kind: 'ig', url: 'https://www.instagram.com/themanilamarketclub/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Greenhills+Shopping+Center+San+Juan' },
    ],
    'Moonlit Market (Aug)': [
      { kind: 'ig', url: 'https://www.instagram.com/themoonlitevents/' },
      { kind: 'ig', url: 'https://www.instagram.com/assemblygrounds/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Assembly+Grounds+The+Rise+Makati' },
    ],
    'The Merry Matcha Market': [
      { kind: 'web', url: 'https://www.google.com/search?q=Merry+Matcha+Market+Gimenez+Gallery+2026' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Gimenez+Gallery+Quezon+City' },
    ],
    'Matcha & Hojicha Collective': [
      { kind: 'ig', url: 'https://www.instagram.com/themodernmarket.ph/' },
      { kind: 'ig', url: 'https://www.instagram.com/silkeventsmgt/' },
    ],
    'Souk Matcha Fest (series)': [
      { kind: 'apply', url: 'https://forms.gle/NPWuFXe5mWNmWxhu5' },
      { kind: 'ig', url: 'https://www.instagram.com/soukpopup/' },
    ],
    'Souk @ Greenhills': [
      { kind: 'apply', url: 'https://forms.gle/NPWuFXe5mWNmWxhu5' },
      { kind: 'ig', url: 'https://www.instagram.com/soukpopup/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Greenhills+Shopping+Center+San+Juan' },
    ],
    'Manila Market Club (Aug editions)': [
      { kind: 'apply', url: 'https://forms.gle/wVAMuaig8UbNFkYcA' },
      { kind: 'ig', url: 'https://www.instagram.com/themanilamarketclub/' },
    ],
    'The Manila Market Club': [
      { kind: 'ig', url: 'https://www.instagram.com/themanilamarketclub/' },
    ],
    'The Social Fair': [
      { kind: 'ig', url: 'https://www.instagram.com/thesocialfair.ph/' },
      { kind: 'ig', url: 'https://www.instagram.com/thesocialfair.merchants/' },
    ],
    'Matcha & Makers Fest': [
      { kind: 'ig', url: 'https://www.instagram.com/assemblygrounds/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Assembly+Grounds+The+Rise+Makati' },
    ],
    'Mini Matcha Festival': [
      { kind: 'web', url: 'https://www.google.com/search?q=Inside+Marikina+Mini+Matcha+Festival' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Marikina+City' },
    ],
    'Manila Matcha Fest': [
      { kind: 'web', url: 'https://matchanese.com/manilamatchafest' },
      { kind: 'ig', url: 'https://www.instagram.com/matchafestph/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=SM+Mall+of+Asia+Pasay' },
    ],
    'Matcha & Arts Fest': [
      { kind: 'apply', url: 'https://bit.ly/WetMarket-MerchantApplication' },
      { kind: 'ig', url: 'https://www.instagram.com/wetmarketph/' },
    ],
    'Matcha Social': [
      { kind: 'web', url: 'https://www.google.com/search?q=Cabana+Club+Matcha+Social+Corner+House+San+Juan' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Corner+House+San+Juan' },
    ],    'Palengke Club': [
      { kind: 'apply', url: 'https://tr.ee/RAtu98obFB' },
      { kind: 'ig', url: 'https://www.instagram.com/palengkeclub/' },
    ],
    'The Fig Archives': [
      { kind: 'apply', url: 'https://forms.gle/6nCSMe3UR4YzB7nf8' },
      { kind: 'ig', url: 'https://www.instagram.com/thefigarchives/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Legaspi+Village+Makati' },
    ],
    'The Solana Market': [
      { kind: 'apply', url: 'https://linktr.ee/thesolanamarket' },
      { kind: 'ig', url: 'https://www.instagram.com/thesolanamarket/' },
    ],
    'The Merkado': [
      { kind: 'ig', url: 'https://www.instagram.com/the.merkado/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Corner+House+San+Juan' },
    ],
    'BGC Art Mart': [
      { kind: 'apply', url: 'https://linktr.ee/bgcartscenter' },
      { kind: 'ig', url: 'https://www.instagram.com/artsatbgc/' },
      { kind: 'ig', url: 'https://www.instagram.com/bgcartscenter/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=BGC+Arts+Center+Taguig' },
    ],
    'The Crafters Marketplace': [
      { kind: 'ig', url: 'https://www.instagram.com/thecraftersmarketplacemanila/' },
      { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Cubao+Expo+Quezon+City' },
    ],
  },

  // matchaOptions removed — the calculator now derives its matcha list from
  // `powders` (full ₱1.8–₱104/g range), so there is one source of truth.
  milkOptions: [
    { l: 'Magnolia fresh dairy — ₱99/L', ml: 0.09925 },
    { l: 'Oatside oat · barista — ₱114/L', ml: 0.11425 },
    { l: 'Barista dairy — ~₱130/L', ml: 0.13 },
    { l: 'Evap/UHT budget — ~₱85/L', ml: 0.085 },
  ],
  pricing: { packaging: 8, additional: 3 }, // ₱/cup defaults — cup+lid / ice+sugar+misc

  // Drinks reference add-on ingredients by name; matcha (global dose) + milk
  // (milkMl) are implicit on every drink. `srp` is the calculator's default.
  drinks: [
    { name: 'Basic Matcha Latte', note: 'the everyday hero', milkMl: 180, ingredients: [], srp: 150,
      desc: 'The benchmark every matcha bar is judged on — ceremonial-grade matcha whisked smooth and poured over milk and ice. Filipino customers treat it as the gateway drink, so a clean, not-too-bitter, lightly sweet build wins the repeat orders; most Metro Manila cafés price it ₱140–180. Nail this one and the rest of the menu sells itself.' },
    { name: 'Ichigo Matcha Latte', note: 'strawberry compote', milkMl: 180, ingredients: ['Strawberry compote'], srp: 180,
      desc: 'The runaway social-media favorite — strawberry compote layered under green matcha and milk for a pink-and-green gradient that photographs beautifully. "Strawberry matcha" is consistently the most-searched flavored matcha in the PH, peaking Dec–May when local Baguio strawberries are cheap. A dependable upsell over the basic latte.' },
    { name: 'Seasalt Matcha Latte', note: 'salted cream foam', milkMl: 180, ingredients: ['Salted cream foam'], srp: 180,
      desc: 'A salted cream-cheese foam cap (the "cheese tea" crossover) floats on top, so you sip bittersweet matcha through a salty-sweet cream layer. It reads premium and carries straight over from milk-tea culture, justifying a ₱20–40 markup. The stir-or-don\'t ritual gives booths a fun interactive hook.' },
    { name: 'Shoyu Matcha', note: 'umami-sweet novelty', milkMl: 180, ingredients: ['Soy + caramel'], srp: 160,
      desc: 'A novelty build where a touch of soy sauce and caramel deepens matcha\'s umami into a savory-sweet, almost butterscotch note. It\'s a conversation-starter / signature item rather than a volume seller — cheap to make and great for standing out at a crowded pop-up. Best aimed at adventurous, returning customers.' },
    { name: 'Pistachio Matcha Latte', note: 'nutty pistachio', milkMl: 180, ingredients: ['Pistachio'], srp: 200,
      desc: 'Pistachio syrup (usually Monin) lends a rich, nutty roundness that tempers matcha\'s grassiness — a "dessert in a cup" that commands the highest price on the menu. The imported syrup is the cost driver, so margins run thinner; position it as a premium treat and finish with a pistachio-crumb garnish.' },
    { name: 'Sakura Matcha Latte', note: 'floral, seasonal', milkMl: 180, ingredients: ['Sakura syrup'], srp: 200,
      desc: 'Delicate cherry-blossom syrup gives a floral, faintly almond aroma and a soft pink tint — a limited seasonal "drop" that creates urgency and buzz around spring and Japan-themed events. Like pistachio, the imported syrup keeps margins tight, so run it as a timed premium special with a strong story.' },
    { name: 'Calamansi Matcha', note: 'citrus, light/no milk', milkMl: 80, ingredients: ['Calamansi + honey'], srp: 160,
      desc: 'A bright local twist — calamansi and honey over matcha, usually served light- or no-milk so the citrus stays crisp and refreshing. It\'s the cheapest add-on on the list and a perfect hot-weather, milk-free option for lactose-avoiders. Distinctly Filipino, which makes it a memorable booth signature.' },
    { name: 'Iced Lychee Matcha', note: 'light & fruity', milkMl: 80, ingredients: ['Lychee'], srp: 180,
      desc: 'Lychee syrup or purée over iced matcha with minimal milk — fruity, floral and very refreshing, riding the same fruit-tea wave as strawberry. It also works as a sparkling / soda variant. A light, crowd-pleasing alternative for guests who find milk lattes too heavy.' },
    { name: 'Horchata Matcha', note: 'cinnamon-rice cream', milkMl: 150, ingredients: ['Horchata mix'], srp: 170,
      desc: 'A cinnamon-rice-milk (horchata) base brings a creamy, dessert-spiced warmth that flatters matcha — comforting and a little unexpected. It leans on the horchata mix for body so it needs less dairy milk, and the cinnamon aroma practically sells itself at a booth. A cozy, autumn-leaning specialty.' },
  ],

  // Reference photos per drink — self-hosted thumbnails (≤640px), real market
  // shots from DuckDuckGo image search, visually validated per drink + globally
  // de-duplicated. Each carries its source page + credit (host).
  drinkImages: {
    'Basic Matcha Latte': [
      { src: '/drinks/basic-matcha-latte/1.jpg', source: 'https://preppykitchen.com/iced-matcha-latte/', credit: 'preppykitchen.com' },
      { src: '/drinks/basic-matcha-latte/2.jpg', source: 'https://www.sweethomecook.com/the-perfect-iced-matcha-latte-recipe/', credit: 'www.sweethomecook.com' },
      { src: '/drinks/basic-matcha-latte/3.jpg', source: 'https://simplyhomecooked.com/iced-matcha-latte/', credit: 'simplyhomecooked.com' },
      { src: '/drinks/basic-matcha-latte/4.jpg', source: 'https://www.mustdorecipes.com/iced-matcha-latte-recipe-thats-creamy-easy-and-healthy/', credit: 'mustdorecipes.com' },
      { src: '/drinks/basic-matcha-latte/5.jpg', source: 'https://www.loveandlemons.com/iced-matcha-latte/', credit: 'cdn.loveandlemons.com' },
      { src: '/drinks/basic-matcha-latte/6.jpg', source: 'https://www.eatingbirdfood.com/iced-matcha-latte/', credit: 'www.eatingbirdfood.com' },
      { src: '/drinks/basic-matcha-latte/7.jpg', source: 'https://gimmedelicious.com/diy-iced-matcha-latte/', credit: 'gimmedelicious.com' },
      { src: '/drinks/basic-matcha-latte/8.jpg', source: 'https://www.modernfarmhouseeats.com/starbucks-iced-matcha-latte/', credit: 'www.modernfarmhouseeats.com' },
    ],
    'Ichigo Matcha Latte': [
      { src: '/drinks/ichigo-matcha-latte/1.jpg', source: 'https://bitezly.com/strawberry-matcha-latte-recipe/', credit: 'bitezly.com' },
      { src: '/drinks/ichigo-matcha-latte/2.jpg', source: 'https://www.sweetsteep.com/how-to-make-a-strawberry-matcha-latte/', credit: 'www.sweetsteep.com' },
      { src: '/drinks/ichigo-matcha-latte/3.jpg', source: 'https://www.sweetsteep.com/how-to-make-a-strawberry-matcha-latte/', credit: 'www.sweetsteep.com' },
      { src: '/drinks/ichigo-matcha-latte/4.jpg', source: 'https://recipesedge.com/iced-strawberry-matcha-latte-recipe/', credit: 'cdn.loveandlemons.com' },
      { src: '/drinks/ichigo-matcha-latte/5.jpg', source: 'https://www.sweetsteep.com/how-to-make-a-strawberry-matcha-latte/', credit: 'www.sweetsteep.com' },
      { src: '/drinks/ichigo-matcha-latte/6.jpg', source: 'https://mytastycurry.com/iced-strawberry-matcha-latte/', credit: 'mytastycurry.com' },
      { src: '/drinks/ichigo-matcha-latte/7.jpg', source: 'https://www.justonecookbook.com/strawberry-matcha-latte/', credit: 'www.justonecookbook.com' },
      { src: '/drinks/ichigo-matcha-latte/8.jpg', source: 'https://www.niemi.ch/2023/05/iced-strawberry-matcha-latte.html', credit: 'blogger.googleusercontent.com' },
    ],
    'Seasalt Matcha Latte': [
      { src: '/drinks/seasalt-matcha-latte/1.jpg', source: 'https://lcarecipes.com/sea-salt-matcha-latte/', credit: 'lcarecipes.com' },
      { src: '/drinks/seasalt-matcha-latte/2.jpg', source: 'https://mealdelights.com/sea-salt-matcha-latte/', credit: 'mealdelights.com' },
      { src: '/drinks/seasalt-matcha-latte/3.jpg', source: 'https://lcarecipes.com/sea-salt-matcha-latte/', credit: 'lcarecipes.com' },
      { src: '/drinks/seasalt-matcha-latte/4.jpg', source: 'https://lcarecipes.com/sea-salt-matcha-latte/', credit: 'lcarecipes.com' },
      { src: '/drinks/seasalt-matcha-latte/5.jpg', source: 'https://www.pinterest.com/pin/matcha-syrup-recipe-video--30328997485454860/', credit: 'i.pinimg.com' },
      { src: '/drinks/seasalt-matcha-latte/6.jpg', source: 'https://www.youtube.com/watch?v=WSuliDq_KSU', credit: 'i.ytimg.com' },
      { src: '/drinks/seasalt-matcha-latte/7.jpg', source: 'https://www.pinterest.com/pin/352828952076077618/', credit: 'i.pinimg.com' },
      { src: '/drinks/seasalt-matcha-latte/8.jpg', source: 'https://ispillice.com/sea-salt-cream-matcha/', credit: 'ispillice.com' },
    ],
    'Shoyu Matcha': [
      { src: '/drinks/shoyu-matcha/1.jpg', source: 'https://kalejunkie.com/iced-strawberry-matcha-latte/', credit: 'kalejunkie.com' },
      { src: '/drinks/shoyu-matcha/2.jpg', source: 'https://sakurajunction.com/2016/10/07/matcha-soy-latte-with-japanese-sweet/', credit: 'sakurajunction.com' },
      { src: '/drinks/shoyu-matcha/3.jpg', source: 'https://storage.googleapis.com/dmqaxjhxjexyue/matcha-soy-milk-latte-recipe.html', credit: 'www.thelittleepicurean.com' },
      { src: '/drinks/shoyu-matcha/4.jpg', source: 'https://thejapaneserose.com/the-matcha-tokyo-plant-based-matcha-latte-in-tokyo/', credit: 'thejapaneserose.com' },
      { src: '/drinks/shoyu-matcha/5.jpg', source: 'https://www.2aussietravellers.com/soy-matcha-latte/', credit: 'www.2aussietravellers.com' },
      { src: '/drinks/shoyu-matcha/6.jpg', source: 'https://www.einfachmalene.de/strawberry-matcha-latte/', credit: 'www.einfachmalene.de' },
      { src: '/drinks/shoyu-matcha/7.jpg', source: 'https://michaschwab.de/matcha-latte-rezept-2024-schritt-fur-schritt-bilder/', credit: 'i.pinimg.com' },
    ],
    'Pistachio Matcha Latte': [
      { src: '/drinks/pistachio-matcha-latte/1.jpg', source: 'https://flashycoffee.com/pistachio-matcha-latte/', credit: 'flashycoffee.com' },
      { src: '/drinks/pistachio-matcha-latte/2.jpg', source: 'https://karmacoffeecafe.com/pistachio-matcha-latte-recipe/', credit: 'karmacoffeecafe.com' },
      { src: '/drinks/pistachio-matcha-latte/3.jpg', source: 'https://karmacoffeecafe.com/pistachio-matcha-latte-recipe/', credit: 'karmacoffeecafe.com' },
      { src: '/drinks/pistachio-matcha-latte/4.jpg', source: 'https://www.easyworklunches.com/pistachio-matcha-latte/', credit: 'www.easyworklunches.com' },
      { src: '/drinks/pistachio-matcha-latte/5.jpg', source: 'https://blenz.com/news/pistachio-matcha-latte/', credit: 'blenz.com' },
      { src: '/drinks/pistachio-matcha-latte/6.jpg', source: 'https://www.shecooksrecipes.com/pistachio-matcha-latte/', credit: 'www.shecooksrecipes.com' },
      { src: '/drinks/pistachio-matcha-latte/7.jpg', source: 'https://www.shecooksrecipes.com/pistachio-matcha-latte/', credit: 'www.shecooksrecipes.com' },
      { src: '/drinks/pistachio-matcha-latte/8.jpg', source: 'https://www.shecooksrecipes.com/pistachio-matcha-latte/', credit: 'www.shecooksrecipes.com' },
    ],
    'Sakura Matcha Latte': [
      { src: '/drinks/sakura-matcha-latte/1.jpg', source: 'https://muchdesserts.com/sakura-matcha-latte/', credit: 'muchdesserts.com' },
      { src: '/drinks/sakura-matcha-latte/2.jpg', source: 'https://sugaryums.com/sakura-latte/', credit: 'sugaryums.com' },
      { src: '/drinks/sakura-matcha-latte/3.jpg', source: 'https://muchdesserts.com/sakura-matcha-latte/', credit: 'muchdesserts.com' },
      { src: '/drinks/sakura-matcha-latte/4.jpg', source: 'https://muchdesserts.com/sakura-matcha-latte/', credit: 'muchdesserts.com' },
      { src: '/drinks/sakura-matcha-latte/5.jpg', source: 'https://muchdesserts.com/sakura-matcha-latte/', credit: 'muchdesserts.com' },
      { src: '/drinks/sakura-matcha-latte/6.jpg', source: 'https://muchdesserts.com/sakura-matcha-latte/', credit: 'muchdesserts.com' },
      { src: '/drinks/sakura-matcha-latte/7.jpg', source: 'https://muchdesserts.com/sakura-matcha-latte/', credit: 'muchdesserts.com' },
      { src: '/drinks/sakura-matcha-latte/8.jpg', source: 'https://sugaryums.com/sakura-latte/', credit: 'sugaryums.com' },
    ],
    'Calamansi Matcha': [
      { src: '/drinks/calamansi-matcha/1.jpg', source: 'https://rezelkealoha.com/sparkling-matcha-calamansi-soda/', credit: 'rezelkealoha.com' },
      { src: '/drinks/calamansi-matcha/2.jpg', source: 'https://www.pinterest.com/pin/matcha-calamansi-sparkling-in-2025--8022105582172127/', credit: 'i.pinimg.com' },
      { src: '/drinks/calamansi-matcha/3.jpg', source: 'https://www.pinterest.com/pin/calamansi-matcha-lemonade-in-2025--414260865743723419/', credit: 'i.pinimg.com' },
      { src: '/drinks/calamansi-matcha/4.jpg', source: 'https://rezelkealoha.com/sparkling-matcha-calamansi-soda/', credit: 'rezelkealoha.com' },
      { src: '/drinks/calamansi-matcha/5.jpg', source: 'https://vulcanpost.com/875295/koppiku-coffee-chain-malaysia-limited-time-matcha-drinks/', credit: 'vulcanpost.com' },
      { src: '/drinks/calamansi-matcha/6.jpg', source: 'https://storage.googleapis.com/dmtkvuvazjuhie/how-to-make-matcha-latte-from-powder.html', credit: 'kalejunkie.com' },
      { src: '/drinks/calamansi-matcha/7.jpg', source: 'https://qaqooking.wiki/all/how-to/how-to-make-teavana-matcha-tea', credit: 'starbucksmelody.com' },
      { src: '/drinks/calamansi-matcha/8.jpg', source: 'https://natruedrinks.com/drinks/cold-matcha-with-coconut/', credit: 'natruedrinks.com' },
    ],
    'Iced Lychee Matcha': [
      { src: '/drinks/iced-lychee-matcha/1.jpg', source: 'https://www.umakemehungry.com/2023/11/keijometo.html', credit: 'blogger.googleusercontent.com' },
      { src: '/drinks/iced-lychee-matcha/2.jpg', source: 'https://www.tiger-corporation.com/en/usa/feature/recipe/blender/matcha-and-lychee-soda/', credit: 'www.tiger-corporation.com' },
      { src: '/drinks/iced-lychee-matcha/3.jpg', source: 'https://www.siftandsimmer.com/matcha-lychee-soda/', credit: 'www.siftandsimmer.com' },
      { src: '/drinks/iced-lychee-matcha/4.jpg', source: 'https://fr.pinterest.com/pin/7740630606106619/', credit: 'i.pinimg.com' },
      { src: '/drinks/iced-lychee-matcha/5.jpg', source: 'https://www.siftandsimmer.com/matcha-lychee-soda/', credit: 'www.siftandsimmer.com' },
      { src: '/drinks/iced-lychee-matcha/6.jpg', source: 'https://momrecipeswap.com/matcha-lychee-iced-tea/', credit: 'momrecipeswap.com' },
      { src: '/drinks/iced-lychee-matcha/7.jpg', source: 'https://www.pinterest.com/pin/lychee-matcha-iced-tea--110338259617499168/', credit: 'i.pinimg.com' },
    ],
    'Horchata Matcha': [
      { src: '/drinks/horchata-matcha/1.jpg', source: 'https://mealdelights.com/horchata-matcha-latte/', credit: 'mealdelights.com' },
      { src: '/drinks/horchata-matcha/2.jpg', source: 'https://www.chocopy.com/horchata-matcha-latte/', credit: 'www.chocopy.com' },
      { src: '/drinks/horchata-matcha/3.jpg', source: 'https://www.mochimommy.com/matcha-horchata/', credit: 'www.mochimommy.com' },
      { src: '/drinks/horchata-matcha/4.jpg', source: 'https://www.pinterest.com/pin/how-to-make-easy-matcha-horchata-latte-ispillice--16325617396325889/', credit: 'i.pinimg.com' },
      { src: '/drinks/horchata-matcha/5.jpg', source: 'https://www.mochimommy.com/matcha-horchata/', credit: 'www.mochimommy.com' },
      { src: '/drinks/horchata-matcha/6.jpg', source: 'https://veggiekinsblog.com/2025/11/17/horchata-matcha-latte/', credit: 'veggiekinsblog.com' },
      { src: '/drinks/horchata-matcha/7.jpg', source: 'https://mealdelights.com/horchata-matcha-latte/', credit: 'mealdelights.com' },
      { src: '/drinks/horchata-matcha/8.jpg', source: 'https://www.mochimommy.com/matcha-horchata/', credit: 'www.mochimommy.com' },
    ],
  },

  // Priced add-on ingredients (₱ per cup) — each self-contained: emoji, market
  // price (reference, overridable in the calculator) + optional reference link.
  // Matcha & milk are the selectors, not here.
  ingredients: [
    { name: 'Strawberry compote', emoji: '🍓', price: 14, link: 'https://tribune.net.ph/2026/04/02/strawberry-prices-in-baguio-drop-as-tourist-numbers-fall' },
    { name: 'Salted cream foam', emoji: '🧀', price: 15, link: 'https://shopee.ph/Emborg-UHT-Whipping-Cream-1L-i.144900856.5540159124' },
    { name: 'Soy + caramel', emoji: '🍶', price: 5, link: null },
    { name: 'Pistachio', emoji: '🥜', price: 34, link: 'https://manila-wine.com/manila-wine-others/monin' },
    { name: 'Sakura syrup', emoji: '🌸', price: 36, link: 'https://manila-wine.com/manila-wine-others/monin' },
    { name: 'Calamansi + honey', emoji: '🍋', price: 8, link: 'https://psa.gov.ph/statistics/price-situationer/selected-agri-commodities' },
    { name: 'Lychee', emoji: '🫧', price: 28, link: null },
    { name: 'Horchata mix', emoji: '🥛', price: 13, link: null },
  ],

  powders: [
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', star: true, name: 'Ritual Matcha Co.', origin: '“Kasane” · 1st-harvest ceremonial · Shizuoka → PH · wholesale + private label',
      taste: 'Deep umami, delicate sweetness, low bitterness — holds up in milk. Built to SUPPLY cafés (1kg bulk + OEM).',
      price: '₱1,250 / 40g · ₱31/g (far less at 1kg)', serving: '~₱62 retail (much less wholesale)',
      hype: '“Trusted by 300+ PH cafés” — the B2B insider pick. Best path to protected margins.', buy: 'ritualmatcha.ph + wholesale form', url: 'https://ritualmatcha.ph' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', star: true, name: 'Matcha Moments', origin: '“Miyu” café blend · 2nd-harvest · Yame, Fukuoka',
      taste: 'Nutty, toasted almond + pecan, savory umami, low bitterness. Best quality-for-price latte base; 500g / 1kg.',
      price: '₱1,760 / 100g · ₱17.6/g', serving: '~₱35', hype: 'Approachable-premium with transparent cultivar/harvest sourcing.', buy: 'matchamoments.ph · Shopee', url: 'https://matchamoments.ph' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Maison Midori', origin: '“Tenshi” Samidori · premium single-cultivar ceremonial · Kyoto',
      taste: 'Creamy, earthy, balanced umami-sweetness, minimal astringency. DTC-only (no wholesale tier yet).',
      price: '₱990 / 40g · ₱24.75/g', serving: '~₱50', hype: '🔥 Most viral + press-covered PH brand of 2025–26 — the marketing magnet. Sells out fast.', buy: 'maisonmidori.com · IG/TikTok', url: 'https://maisonmidori.com' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', star: true, name: 'Nokori', origin: '“Komo” · latte-tuned everyday ceremonial blend · Uji, Kyoto',
      taste: 'Mild, creamy, soft pistachio, custard-like, low astringency — designed not to fight the milk.',
      price: 'from ₱839 / 60g · ₱14/g', serving: '~₱28 (best boutique margin)', hype: 'Strong TikTok presence; the everyday-latte favorite. Small-batch drops sell out.', buy: 'nokorimatcha.com · Lazada', url: 'https://nokorimatcha.com' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Sobamatsu', origin: 'budget latte-oriented · Japan-sourced',
      taste: 'Light, grassy, latte-leaning — a cheap everyday option for high-volume value pricing.',
      price: '~₱600 / 50g · ₱12/g', serving: '~₱24', hype: 'Strong viral TikTok buzz as the affordable everyday pick.', buy: 'Shopee / Lazada', url: 'https://shopee.ph/search?keyword=sobamatsu%20matcha' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Little Retail PH', origin: 'Pure Unsweetened · culinary + ceremonial grades · QC, PH (Japan region unspecified)',
      taste: 'No-frills unsweetened powder you sweeten yourself — the budget workhorse for high-volume value lattes.',
      price: 'Culinary 100g ₱180 · ₱1.8/g · 1kg ₱1,188 (₱1.19/g) · Ceremonial 100g ₱3.25/g', serving: '~₱2.4–3.6 / 2g (culinary)',
      hype: 'The cheapest credible ₱/g in PH; ranked #3 in my-best\'s 2026 PH matcha guide.', buy: 'littleretailph.com · Lazada · Shopee', url: 'https://littleretailph.com/products/pure-unsweetened-matcha-powder' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Matcha Mill', origin: 'single-origin by prefecture (Kirishima/Uji/Yame/Shizuoka) · PH\'s first local stone-miller · Davao',
      taste: 'Single-origin Kirishima: nutty/creamy — almond, pistachio, avocado, heavy creamy body, low-moderate bitterness.',
      price: 'Single-origin 100g ₱840 · ₱8.4/g · 1kg ₱7,392 (₱7.4/g) · organic up to ₱24/g', serving: '~₱16.8 / 2g (single-origin)',
      hype: 'Niche serious-hobbyist favorite — the only PH brand milling fresh leaf locally (“fresher than imported tins”).', buy: 'matcha-mill.com (free ship ₱1,999+)', url: 'https://matcha-mill.com/products/kirishima-kagoshima-matcha' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Moonbug Matcha', origin: '“OG” Shizuoka ceremonial blend · JAS + USDA organic · Shizuoka/Kagoshima/Uji/Yame',
      taste: 'Smooth, creamy, grassy with mild nutty umami + bright astringency. Polarizing — some find it “too grassy” unsweetened.',
      price: '30g ₱700 · ₱23.3/g · 100g ₱1,900 (₱19/g)', serving: '~₱38–47 / 2g',
      hype: 'Buzzy organic daily-driver (~4.5/5 on matcha TikTok); the certified-organic value pick.', buy: 'moonbugmatcha.com · Lazada · Shopee', url: 'https://moonbugmatcha.com/products/authentic-ceremonial-matcha' },
    { cat: 'ph', catlabel: '🇵🇭 PH Homegrown', name: 'Made in Matcha', origin: '“Everyday” blend / “Ukiyo” single-origin · Kagoshima (Yabukita) · locally stone-milled “farm-to-cup”',
      taste: 'Everyday: balanced, grassy, light umami, gentle bitterness. Ukiyo: smooth, umami-rich, creamy, subtly sweet.',
      price: 'Everyday 30g ₱950 · ₱31.7/g · Ukiyo single-origin 30g ₱1,800 (₱60/g)', serving: '~₱63 / 2g (Everyday) · ~₱120 (Ukiyo)',
      hype: 'Buzzy Filipino “farm-to-cup” brand — Kagoshima leaf stone-ground locally, sold on cultivar transparency.', buy: 'madeinmatcha.com', url: 'https://madeinmatcha.com/products/everyday-matcha-30g-blend' },
    { cat: 'jp', catlabel: '🇯🇵 Japanese · in PH', star: true, name: 'Yamamasa Koyamaen', origin: '“Matsukaze / Ogurayama” · ceremonial · Uji, Kyoto (est. 1704)',
      taste: 'Ogurayama: creamy, velvety, umami + sweet, floral-nutty. Matsukaze: vegetal, light, holds color in milk.',
      price: '30g cans ~₱800–2,100 · ₱27–70/g', serving: '~₱53 – ₱93', hype: 'Very high on TikTok, near Ippodo tier — in stock at Midori PH, sells out fast.', buy: 'Midori Matcha PH · japanmatcha.ph', url: 'https://midorimatchaph.com/collections/yamamasa-koyamaen' },
    { cat: 'jp', catlabel: '🇯🇵 Japanese · in PH', name: 'The Matcha Tokyo', origin: '“Tokyo Rich / Japan Premium” · 100% organic · Kagoshima/Uji leaf',
      taste: 'Bold umami, low astringency, grassy, rich bitter finish. Tokyo Rich is latte-optimized.',
      price: 'Tokyo Rich ₱1,540/20g (₱77/g)', serving: '~₱154–220 (retail — negotiate B2B)', hype: 'High — viral on TikTok, top Manila matcha; 13+ PH cafés.', buy: 'PH cafés · GrabFood · order site', url: 'https://thematchatokyo-ph.tablevibe.co/' },
    { cat: 'jp', catlabel: '🇯🇵 Japanese · in PH', name: 'Tsujiri', origin: '“Ume No Shiro” ceremonial · Uji, Kyoto heritage (est. 1860) · tins sold in-store at PH cafés',
      taste: 'Smooth, creamy ceremonial Uji with balanced sweetness-to-bitterness — the “beginner\'s ceremonial,” vegetal-forward, mild umami.',
      price: '30g / 100g tins · ≈ ₱48/g (est. from import; no confirmed PH online price)', serving: '~₱97 / 2g (est.)',
      hype: '160-yr Uji-Kyoto matcha dynasty — soft-serve queues & ceremonial tins from one heritage. Ask in-store for tins.', buy: 'TSUJIRI PH cafés (Podium, SM Aura, Greenbelt 5…) · FB tsujiri.ph', url: 'https://www.facebook.com/tsujiri.ph/' },
    { cat: 'jp', catlabel: '🇯🇵 Japanese · in PH', name: 'Ito En', origin: 'Japan\'s #1 green-tea brand (Shizuoka, 1966) · mass-market · PH shelf SKU = sweetened matcha-latte mix',
      taste: 'Sweet Matcha: mellow, sweet, lightly grassy — a ready-to-mix latte flavor (sugar-added), NOT a bitter ceremonial whisk.',
      price: 'Sweet Matcha mix 120g ≈ ₱730 · ₱6/g (sweetened) · pure culinary ~₱11.6/g (not stocked in PH)', serving: '~₱12 / 2g (sweetened mix)',
      hype: 'The easy supermarket “matcha latte” grab — cheap & everywhere, but a sweetened mix, not pure matcha (verify live PHP price).', buy: 'Lazada PH (official store) · Shopee · SM / Landers', url: 'https://www.lazada.com.ph/ito-en/' },
    { cat: 'import', catlabel: '🌏 Imported', star: true, name: 'Marukyu-Koyamaen', origin: '“Aoarashi” (hero) / “Wakatake” (bulk) · Uji, Kyoto (est. ~1704)',
      taste: 'Aoarashi: brisk, bold, grassy, vibrant green — a ceremonial that SURVIVES milk. Wakatake = culinary bulk.',
      price: 'PH ₱1,300 / 40g · ₱33/g', serving: '~₱40–65', hype: 'Prestige tea-ceremony supplier; Aoarashi is the PH cult-favorite. Chronic sellouts.', buy: 'Midori Matcha PH · Japan Matcha PH', url: 'https://midorimatchaph.com/collections/marukyu-koyamaen' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Ippodo', origin: '“Ikuyo” (latte) / “Sayaka” (premium) · Uji/Kyoto (est. 1717)',
      taste: 'Ikuyo: balanced, mild umami, snappy, nutty/white-chocolate, photogenic green. The prestige benchmark.',
      price: 'PH café 100g ₱3,000 · ₱30/g', serving: '~₱60 (₱90 at 3g)', hype: 'Top benchmark; won\'t ship to PH direct — buy via resellers. Shortage + sellouts.', buy: 'MODO @ Mitsukoshi BGC · Matcha Tana', url: 'https://modo.ph/collections/ippodo-tea' },
    { cat: 'import', catlabel: '🌏 Imported', star: true, name: 'Naoki Matcha', origin: '“Barista Blend” · latte/barista grade · Kagoshima + Uji leaf',
      taste: 'Bold, earthy, roasty — built to cut through milk. Great-value café-quality; B2B program available.',
      price: '40g ≈ ₱1,025 · ₱26/g (culinary ~₱8.5/g)', serving: '~₱52', hype: 'Loved on TikTok/Lemon8 as best-value café-quality; gripe: duller color.', buy: 'Shopee PH · direct import · B2B', url: 'https://naokimatcha.com/products/barista-blend-matcha' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Encha', origin: '“Latte / Barista Grade” · organic single-origin Uji',
      taste: 'Latte Grade: bold, cuts through milk. Barista: nutty, toasted, chocolate. Best value in 500g bulk.',
      price: 'Latte 500g ₱17/g · Barista 500g ₱11/g', serving: 'Latte ~₱34 · Barista ~₱22', hype: 'Popular organic/value pick — import-only, and a 2025 heavy-metals flag worth knowing.', buy: 'Import-only · Lazada cross-border', url: 'https://encha.com/collections/all' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Aiya', origin: '“Culinary” (Ceremonial for premium) · Nishio, Aichi (since 1888)',
      taste: 'Culinary: bolder, mildly astringent, strong enough for milk. World\'s largest producer — café bulk workhorse.',
      price: 'Culinary 100g ₱18/g · 1kg ~₱9.7/g', serving: '~₱19–20 (bulk culinary)', hype: 'Reliable café workhorse; enthusiasts rate ceremonial “mid”. No confirmed PH distributor.', buy: 'Import via Aiya America / wholesale', url: 'https://aiya-america.com/retail/matcha-products/' },
    { cat: 'import', catlabel: '🌏 Imported', name: "Rocky's Matcha", origin: 'ceremonial blends + single cultivars · US brand, Japanese leaf (Yame/Uji)',
      taste: 'Smooth, creamy, nutty, natural sweetness, low bitterness. A TikTok cult darling.',
      price: '₱2,088 / 20g (US$36) · ₱104/g · 100g ≈ ₱45/g', serving: '~₱209 / 2g flagship · ~₱90 at 100g', hype: 'Huge on TikTok but pricey & import-only — sole PH reseller (Glow PH) is out of stock; buy direct via DHL.', buy: 'rockysmatcha.com (DHL import) · Glow PH (OOS)', url: 'https://www.rockysmatcha.com/products/rockys-matcha-ceremonial-blend-matcha-20g' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Jade Leaf', origin: 'Barista Edition / Teahouse · organic first-harvest · US brand, Uji + Kagoshima leaf',
      taste: 'Smooth, mild nuttiness + umami, made to cut through milk — an affordable, consistent gateway latte matcha.',
      price: 'Barista 50g ₱1,698 (₱34/g) · 1lb bulk ₱24.4/g · ceremonial 30g ₱50/g', serving: '~₱50–70 / 2g (Barista)',
      hype: 'Top US-market organic “gateway” brand — affordable & consistent, not a connoisseur single-origin.', buy: 'Ubuy PH (cross-border import) · jadeleafmatcha.com', url: 'https://www.ubuy.com.ph/brand/jade-leaf-matcha' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Hibiki-an', origin: 'single-estate Uji, Kyoto · direct-from-Japan grower · Superior → Premium → Super Premium → Pinnacle',
      taste: 'Super Premium: bright, thick, umami-rich, koicha-capable ceremonial. Superior = everyday usucha entry; Pinnacle = smoothest flagship.',
      price: '₱30–90/g across grades · Super Premium 40g US$39 (₱59.5/g) · 120g refill ₱49.8/g', serving: '~₱61–119 / 2g',
      hype: 'Cult Uji grower selling genuine farm-direct ceremonial — real Kyoto leaf without a middleman.', buy: 'hibiki-an.com (ships to PH, direct import + duties)', url: 'https://www.hibiki-an.com/sp/product_info.php/products_id/349' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Nakamura Tokichi', origin: 'historic Uji tea house (est. 1854) · usucha → flagship koicha · Uji, Kyoto',
      taste: 'Fuji-no-Shiro: delicate bitterness, balanced astringency, clean light finish — versatile for usucha or lattes.',
      price: 'Fuji-no-Shiro 30g ¥2,000 ≈ ₱26/g · Standard 100g ₱46.8/g · flagship Uji-no-Mukashi ₱117/g', serving: '~₱52 / 2g (entry) · ~₱234 (flagship)',
      hype: '170-year-old Uji institution — authentic ceremonial Kyoto matcha shipped straight from the source.', buy: 'global.tokichi.jp (ships to PH via DHL + duties)', url: 'https://global.tokichi.jp/products/mc2' },
    { cat: 'import', catlabel: '🌏 Imported', name: 'Hoshinoen (Yame no Hana)', origin: 'premium Yame, Fukuoka (Hoshino Seichaen) · ceremonial Okumidori · TikTok-viral',
      taste: 'Smooth, nutty-toasted, lightly smoky, subtly sweet with almost no bitterness — creamy in lattes; rated ~10/10 for the price.',
      price: '30g ¥2,500 ≈ ₱32.5/g (origin) · ~₱45–60/g landed after forwarder', serving: '~₱65 / 2g (origin) · ~₱90–120 landed',
      hype: 'TikTok-viral Yame matcha (“10/10 for the price”) — but import/forwarder-only & almost always SOLD OUT.', buy: 'Wakokoro Tea (ships from Japan) · forwarder — no PH reseller', url: 'https://wakokoro-tea.com/products/matcha-yame-no-hana-by-hoshino-seichaen-40g' },
  ],

  // Top 10 indie matcha-drink competitors (Metro Manila). Ranked from 30 researched
  // brands; ⭐ rating, review count & open-status live-verified on Google Maps, 2026-06-24.
  competitors: [
    { rank: 1, name: 'Matchanese', region: 'north', format: 'Kiosk · matcha bar', area: 'SM North EDSA + The Podium · QC/Mandaluyong', price: 190, band: 'mid', rating: 4.7, reviews: 289, open: true, ig: 18800,
      sig: 'Signature Matchanese Latte',
      menu: [{ i: 'Signature Latte', p: 190 }, { i: 'Quatro Spanish', p: 220 }, { i: 'Strawberry', p: 250 }, { i: 'Einspanner', p: 290 }],
      sourcing: 'Claims 100% organic Kyoto matcha, hand-whisked; pick strength levels 1–3.',
      hook: "Bills itself as Manila's first homegrown specialty matcha bar — customizable strength, accessible price.",
      opened: 'Online 2021 · café 2023', threat: 'strong',
      scale: '2 mall kiosks + mobile event bar',
      healthTxt: '🟢 Growing',
      links: [{ kind: 'web', url: 'https://matchanese.com/' }, { kind: 'ig', url: 'https://www.instagram.com/matchaneseph/' }, { kind: 'fb', url: 'https://www.facebook.com/matchanese/' }, { kind: 'tiktok', url: 'https://www.tiktok.com/@matchaneseph' }, { kind: 'order', url: 'https://matchanese.cococart.co/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Matchanese%20SM%20North%20EDSA%20Quezon%20City' }] },

    { rank: 2, name: 'Matcha Later', region: 'central', format: 'Slow bar · women-owned', area: 'Poblacion, Makati', price: 240, band: 'premium', rating: 4.6, reviews: 157, open: true, ig: 13100,
      sig: 'Kumo (cloud-milk matcha)',
      menu: [{ i: 'Kumo', p: 240 }, { i: 'Caramiso', p: 250 }, { i: 'Kumo Berry', p: 260 }, { i: 'Tiramisu Latte', p: 250 }],
      sourcing: "Ceremonial matcha + premium hojicha, Uji/Kyoto; sells own 'Matcha Yuu' powder.",
      hook: 'Intimate Japanese slow bar, whisked in front of you; signature salted-caramel-miso Caramiso.',
      opened: '2024', threat: 'strong',
      scale: 'Single slow bar, ~8–10 seats',
      healthTxt: '🟢 Growing · long waits',
      links: [{ kind: 'ig', url: 'https://www.instagram.com/matchalaterph/' }, { kind: 'fb', url: 'https://www.facebook.com/matchalaterph/' }, { kind: 'tiktok', url: 'https://www.tiktok.com/@matchalaterph' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Matcha%20Later%20Poblacion%20Makati' }] },

    { rank: 3, name: 'Matcha Go!', region: 'south', format: 'Community cafe', area: 'Pilar Village, Las Piñas', price: 250, band: 'mid', rating: 4.9, reviews: 164, open: true, ig: 1961,
      sig: 'Premium Grade Matcha (oat latte)',
      menu: [{ i: 'Premium Grade', p: 250 }, { i: 'Ceremonial', p: 310 }, { i: 'Ichigo', p: 300 }, { i: 'Sea Salt Cream', p: 260 }],
      sourcing: 'Two self-labeled grades: Premium ₱250 / Ceremonial ₱310; region not named. Oat-milk default.',
      hook: 'Slow-living community cafe — journal & crochet clubs, whisking workshops, sustainability touch.',
      opened: '2024', threat: 'moderate',
      scale: 'Single neighborhood cafe (2nd branch teased)',
      healthTxt: '🟢 Growing · 4.9★',
      links: [{ kind: 'ig', url: 'https://www.instagram.com/ph.matchago/' }, { kind: 'fb', url: 'https://www.facebook.com/phmatchago/' }, { kind: 'tiktok', url: 'https://www.tiktok.com/@ph.matchago' }, { kind: 'order', url: 'https://www.foodpanda.ph/restaurant/kxn4/matcha-go' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Matcha%20Go%20Cafe%20Pilar%20Village%20Las%20Pinas' }] },

    { rank: 4, name: 'OH HEY THERE', region: 'south', format: 'Cafe · founder-run', area: 'BF Homes, Aguirre Ave., Parañaque', price: 290, band: 'premium', rating: 4.9, reviews: 284, open: true, ig: 6089,
      sig: 'Banana Pudding Matcha',
      menu: [{ i: 'Banana Pudding', p: 290 }, { i: 'Banana Cream', p: 270 }, { i: 'Sesame Cream', p: 270 }, { i: 'Pistachio Cream', p: 270 }],
      sourcing: 'Claims 100% Japanese green-tea matcha; no named grade/region.',
      hook: 'Queer-safe, inclusive cafe by two women creatives; playful cream-matcha flavors.',
      opened: 'Mar 2024', threat: 'strong',
      scale: 'Single founder-run cafe',
      healthTxt: '🟢 Growing · 4.9★',
      links: [{ kind: 'web', url: 'https://ohheythere.cafe/' }, { kind: 'ig', url: 'https://www.instagram.com/ohheythere.matchacafe/' }, { kind: 'fb', url: 'https://www.facebook.com/ohheythere.studiocafe/' }, { kind: 'tiktok', url: 'https://www.tiktok.com/@ohheythere.matchacafe' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=OH%20HEY%20THERE%20Matcha%20Cafe%20BF%20Homes%20Paranaque' }] },

    { rank: 5, name: 'Little Matcha Studio', region: 'north', format: 'Slow bar · micro-indie', area: 'Sta. Mesa Heights / Banawe, QC', price: 220, band: 'mid', rating: 4.8, reviews: 18, open: true, ig: 984,
      sig: 'Iced Matcha Latte (Uji · oat)',
      menu: [{ i: 'Pure Matcha', p: 200 }, { i: 'Flat Green', p: 220 }, { i: 'Matcha Latte', p: 220 }, { i: 'Cookie Butter', p: 260 }],
      sourcing: 'Uji, Kyoto matcha; oat milk by default; also sells retail powder.',
      hook: 'Cozy slow bar, everything on oat milk — the genuine small/new micro-indie of the list.',
      opened: '2025', threat: 'niche',
      scale: 'Single nook · newest & smallest (2025)',
      healthTxt: '🟢 New · 18 reviews',
      links: [{ kind: 'ig', url: 'https://www.instagram.com/littlematchastudioph/' }, { kind: 'fb', url: 'https://www.facebook.com/61584763546947' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Little%20Matcha%20Studio%20Banawe%20Quezon%20City' }] },

    { rank: 6, name: 'Shizu Matcha Bar', region: 'north', format: 'Japanese tea house', area: 'Morning Breeze, Caloocan (+ QC)', price: 250, band: 'premium', rating: 4.5, reviews: 139, open: true, ig: 9887,
      sig: 'Malted Milk Matcha',
      menu: [{ i: 'Malted Milk', p: 250 }, { i: 'Einspanner', p: 250 }, { i: 'Banana Pudding', p: 280 }, { i: 'Strawberry', p: 230 }],
      sourcing: 'Claims premium first-flush (ichibancha) matcha, whisked to order. Spend ₱500–1,000/head.',
      hook: 'Contemporary Japanese tea house; first-flush matcha; playful cold-whisk dango.',
      opened: '2024', threat: 'moderate',
      scale: 'Small indie · 2 branches (Caloocan + QC)',
      healthTxt: '🟢 Growing',
      links: [{ kind: 'ig', url: 'https://www.instagram.com/shizumatchabar/' }, { kind: 'tiktok', url: 'https://www.tiktok.com/@shizumatchabar' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Shizu%20Matcha%20Bar%20Morning%20Breeze%20Caloocan' }] },

    { rank: 7, name: 'Kokorobi Matcha', region: 'north', format: 'Slow bar · women-owned', area: 'Marikina Heights, Marikina', price: 320, band: 'premium', rating: 4.8, reviews: 56, open: true, ig: 2533,
      sig: 'Premium Kokorobi Matcha Latte',
      menu: [{ i: 'Premium Latte', p: 320 }, { i: 'Pistachio Cream', p: 300 }, { i: 'Seasalt Vanilla', p: 250 }, { i: 'Powder tins', p: 990 }],
      sourcing: 'JAS-organic first-harvest Uji/Wazuka, stone-milled; sells retail powder line.',
      hook: 'Mindfulness slow bar — single-origin JAS-organic first-harvest Uji, not a generic blend.',
      opened: '2025', threat: 'niche',
      scale: 'Single cafe + powder line + pop-ups',
      healthTxt: '🟢 Growing',
      links: [{ kind: 'web', url: 'https://kokorobimatcha.com/' }, { kind: 'ig', url: 'https://www.instagram.com/kokorobimatcha/' }, { kind: 'fb', url: 'https://www.facebook.com/Kokorobimatcha/' }, { kind: 'tiktok', url: 'https://www.tiktok.com/@kokorobimatcha' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Kokorobi%20Matcha%20Marikina' }] },

    { rank: 8, name: 'Matcha Folk', region: 'north', format: 'Matcha-only bar', area: 'Lamp Quarters, Marikina', price: 250, band: 'mid', rating: 4.5, reviews: 13, open: true, ig: 9200,
      sig: 'Mango Matcha',
      menu: [{ i: 'Mango Matcha', p: 250 }, { i: 'Earl Grey Matcha', p: 260 }, { i: 'Matcha Float', p: null }, { i: 'range ₱220–290', p: null }],
      sourcing: 'Sourcing not disclosed. Drinks ₱220–290.',
      hook: 'Matcha-only bar, rotating variations whisked daily; grew from pop-ups to a permanent shop.',
      opened: 'Shop 2025 (pop-up roots)', threat: 'moderate',
      scale: 'Single shop · new (from pop-up) · long queues',
      healthTxt: '🟢 New · queues',
      links: [{ kind: 'ig', url: 'https://www.instagram.com/matchafolk/' }, { kind: 'fb', url: 'https://www.facebook.com/p/matcha-folk-61565357906355/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Matcha%20Folk%20Lamp%20Quarters%20Marikina' }] },

    { rank: 9, name: 'Matcha Mama', region: 'north', format: 'Cafe · multi-location', area: 'Multi-kiosk QC/BGC — White Plains · Forbes Town · Greenhills', price: 160, band: 'mid', rating: 4.3, reviews: 39, open: true, ig: 14600,
      sig: 'Spanish Matcha',
      menu: [{ i: 'Matcha Latte', p: 160 }, { i: 'Spanish Matcha', p: 170 }, { i: 'Lavender', p: 190 }, { i: 'Horchata', p: 210 }],
      sourcing: 'Uji matcha, 3 tiers (classic/ceremonial/single-cultivar); retail powder & ecommerce.',
      hook: 'Playful pink-green brand, cheapest entry (₱160); multi-tier Uji powder. A cautionary case.',
      opened: '2023', threat: 'moderate',
      scale: '~4 footprints + ecommerce — but a mall branch just closed',
      note: 'Rotates mall kiosks (now White Plains, Forbes Town & Greenhills per its IG); BGC Mitsukoshi branch closed. Claimed 296K TikTok unverified (likely a different brand).',
      healthTxt: '🟡 Closed a branch',
      links: [{ kind: 'web', url: 'https://matchamamaclub.com/' }, { kind: 'ig', url: 'https://www.instagram.com/matchamama.ph/' }, { kind: 'fb', url: 'https://www.facebook.com/matchamama.ph/' }, { kind: 'tiktok', url: 'https://www.tiktok.com/@matchamamaclub' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Matcha%20Mama%20Clubhouse%20Katipunan%20Quezon%20City' }] },

    { rank: 10, name: 'Matcha Bar', region: 'central', format: 'Vegan slow bar · est. 2018', area: 'Legazpi Village, Makati (+ Davao, Siargao)', price: 310, band: 'premium', rating: 4.5, reviews: 307, open: true, ig: 7172,
      sig: 'Matcha Signature (+ nama chocolate)',
      menu: [{ i: 'Signature', p: 310 }, { i: 'Hikari', p: 280 }, { i: 'Hanagi', p: 270 }, { i: 'London Fog', p: 270 }],
      sourcing: 'Claims 100% premium Japanese matcha, café-imported; named cultivars; fully vegan, all house-made.',
      hook: 'Vegan slow-bar ritual — matcharistas hand-whisk tableside; the established benchmark of the set.',
      opened: '2018', threat: 'strong',
      scale: 'Established mini-chain · 3 branches (1 in MM)',
      healthTxt: '🟢 Established · 2018',
      links: [{ kind: 'web', url: 'https://www.welovematchabar.com/' }, { kind: 'ig', url: 'https://www.instagram.com/matchabarph/' }, { kind: 'fb', url: 'https://www.facebook.com/matchabarph' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Matcha%20Bar%20Legazpi%20Village%20Makati' }] },

    // ===== TOP / BENCHMARK BRANDS (established players — study their products) =====
    { tier: 'giant', rank: 1, name: 'The Matcha Tokyo', region: 'south', format: 'Organic matcha chain', area: '9+ mall branches · MOA flagship, Pasay', price: 250, band: 'premium', rating: 4.9, reviews: 1183, open: true, ig: 19800,
      sig: 'Iced Matcha Latte (PH-exclusive Ube Matcha Latte ₱210)',
      menu: [{ i: 'Iced Matcha Latte', p: 250 }, { i: 'Ube Matcha Latte (PH-exclusive)', p: 210 }, { i: 'Matcha Salted Cream', p: 260 }, { i: 'Warabi Mochi Matcha Latte', p: 280 }, { i: 'Matcha Soft Serve', p: null }, { i: 'Seasonal Matcha Frozen', p: 280 }],
      sourcing: '100% organic ceremonial Japanese matcha the brand grows itself; oat/soy/almond options + adjustable sweetness.',
      hook: 'Tokyo-born organic-matcha chain — the mall-dominant market leader.',
      scale: '~9 Metro Manila mall branches; MOA flagship has a zen garden + DIY whisking',
      opened: 'Tokyo origin · multi-branch', threat: 'strong',
      healthTxt: '🏆 Market leader',
      links: [{ kind: 'web', url: 'https://www.the-matcha.tokyo/' }, { kind: 'ig', url: 'https://www.instagram.com/the.matcha.tokyo.ph/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=The%20Matcha%20Tokyo%20SM%20Mall%20of%20Asia' }] },

    { tier: 'giant', rank: 2, name: 'Tsujiri', region: 'south', format: 'Heritage Uji chain (1860)', area: '6 prime-mall branches · S Maison, Pasay', price: 169, band: 'mid', rating: 4.3, reviews: 144, open: true, ig: 18100,
      sig: 'Signature O-Matcha (Tsujiri Sundae ₱285 is the icon)',
      menu: [{ i: 'Signature O-Matcha', p: 169 }, { i: 'Yuzu O-Matcha', p: 193 }, { i: 'Matcha Float', p: 269 }, { i: 'Tsujiri Sundae', p: 285 }, { i: 'Matcha Soft Serve', p: 206 }, { i: 'Uji Sunrise kakigori', p: 325 }],
      sourcing: 'Ceremony-grade Uji matcha; 1860 Kyoto heritage, served in traditional ceramic bowls.',
      hook: '160-year Uji-Kyoto heritage; dessert-forward sundaes & shaved ice.',
      scale: '6 Metro Manila mall branches (S Maison, Podium, Greenbelt 5, Rockwell, Greenhills)',
      opened: 'Est. 1860 · Uji', threat: 'strong',
      healthTxt: '🏆 Heritage brand',
      links: [{ kind: 'web', url: 'https://tsujiri-global.com/' }, { kind: 'ig', url: 'https://www.instagram.com/tsujiri_ph/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Tsujiri%20S%20Maison%20Conrad%20Manila' }] },

    { tier: 'giant', rank: 3, name: 'Chotto Matcha', region: 'central', format: 'PH specialty chain', area: '4 BGC/Makati/Pasig branches', price: 205, band: 'mid', rating: 4.6, reviews: 734, open: true, ig: 9896,
      sig: 'Iced Authentic Matcha Latte (Dirty Matcha ₱240 best-seller)',
      menu: [{ i: 'Iced Authentic Matcha Latte', p: 205 }, { i: 'Local Matcha Latte', p: 205 }, { i: 'Dirty Matcha', p: 240 }, { i: 'Hanami Dango Matcha', p: 250 }, { i: 'Banana Pudding Matcha', p: 270 }, { i: 'Marshmallow Cloudy Matcha', p: null }],
      sourcing: 'Ceremonial Shizuoka / Mt. Fuji matcha; offers Authentic + Local grade tiers to taste-compare.',
      hook: 'Cult PH chain by two Japanese sisters; grade-tier menu & dirty matcha.',
      scale: '4 branches (Little Tokyo Makati, Forbes Town & Park Triangle BGC, Arcovia Pasig) + Tokyo',
      opened: 'PH-founded · from Asakusa', threat: 'strong',
      healthTxt: '🏆 Cult chain',
      links: [{ kind: 'web', url: 'https://www.chottomatcha.net/' }, { kind: 'ig', url: 'https://www.instagram.com/chottomatchaph/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Chotto%20Matcha%20Makati%20Legazpi' }] },

    { tier: 'giant', rank: 4, name: 'SUPER MATCHA', region: 'central', format: 'Korean cult brand', area: 'SM Megamall + Glorietta', price: 260, band: 'premium', rating: 4.5, reviews: 173, open: true, ig: 1714,
      sig: 'Super Matcha Latte (Korean organic)',
      menu: [{ i: 'Super Matcha Latte (reg)', p: 260 }, { i: 'Super Matcha Latte (lg)', p: 290 }, { i: 'Ensaymatcha (PH-exclusive)', p: null }, { i: 'Oat Cream Bori Latte (caffeine-free)', p: null }, { i: 'Burnt-rice Matcha Soft Serve', p: null }],
      sourcing: 'Certified-organic Korean matcha — lighter, floral, low-bitterness; vegan + gluten-free desserts.',
      hook: 'Seoul cult brand — beginner-friendly Korean-style matcha, made in front of you.',
      scale: 'SM Megamall flagship + Glorietta (Seoul brand, est. 2017)',
      opened: '2026 PH · Seoul 2017', threat: 'strong',
      healthTxt: '🏆 New · Korean',
      links: [{ kind: 'web', url: 'https://supermatcha.net/' }, { kind: 'ig', url: 'https://www.instagram.com/supermatcha.philippines/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Super%20Matcha%20SM%20Megamall' }] },

    { tier: 'general', rank: 11, name: 'MODO', region: 'central', format: 'Ultra-premium Ippodo cafe', area: 'Mitsukoshi BGC (B1), Taguig', price: 460, band: 'premium', rating: 4.7, reviews: 32, open: true, ig: null,
      sig: 'Iced Matcha Latte ₱460 (hot ceremonial up to ₱795)',
      menu: [{ i: 'Iced Matcha Latte', p: 460 }, { i: 'Matcha Cafe Latte (Ippodo + Unir coffee)', p: 705 }, { i: 'Ceremonial Matcha Latte (hot)', p: 795 }, { i: 'House Latte', p: 280 }, { i: 'Yamato Ceremonial tin (retail)', p: 1500 }],
      sourcing: 'Ippodo (Kyoto, est. 1717) ceremonial matcha + Unir specialty coffee + Batangas pasteurized milk.',
      hook: 'Ultra-premium Ippodo matcha inside a Japanese food & living concept.',
      scale: 'Single concept store, Mitsukoshi BGC (B1)',
      opened: 'Ippodo · Kyoto 1717', threat: 'niche',
      healthTxt: '🟢 Ultra-premium niche',
      links: [{ kind: 'web', url: 'https://modo.ph/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=MODO%20Mitsukoshi%20BGC' }] },

    // ===== STRAIGHT FROM JAPAN — Japan-only houses (NOT available in PH) · 6 ✨unique + 4 🌟iconic =====
    { tier: 'japan', rank: 1, spotlight: 'unique', name: 'Horii Shichimeien', region: 'japan', format: 'Heritage Uji tea garden', area: 'Uji, Kyoto (near Byōdōin)', price: 600, band: 'mid', rating: 3.1, reviews: 5, open: true, ig: 13400,
      sig: 'Café usucha tasting — matcha from their own Okunoyama garden',
      menu: [{ i: 'Café usucha tasting + sweet', p: 600 }, { i: 'Matcha "Seiri-no" flagship (20g)', p: 3780 }, { i: 'Matcha "Uji Mukashi" (30g)', p: 2484 }, { i: 'Okunoyama Gyokuro', p: null }],
      sourcing: 'Sole grower of "Okunoyama" — the last of Uji\'s seven Muromachi-era famous gardens; own registered cultivar "Seiri-no".',
      hook: '600-year heritage garden; the family invented the modern tencha machine (1924).',
      scale: 'Tiny family tea producer + tasting room, Uji',
      healthTxt: '🍵 Uji · since 1879', opened: '1879 · garden since 14th c.', threat: 'niche',
      links: [{ kind: 'web', url: 'https://horiishichimeien.com/en-sb' }, { kind: 'ig', url: 'https://www.instagram.com/horiishichimeien/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Horii%20Shichimeien%20Uji' }] },

    { tier: 'japan', rank: 2, spotlight: 'unique', name: 'Sakurai Japanese Tea Experience', region: 'japan', format: 'Tea lab + tea-cocktail bar', area: 'Minami-Aoyama / Omotesandō, Tokyo', price: 2500, band: 'premium', rating: 4.6, reviews: 46, open: true, ig: 34700,
      sig: 'Tea Course tasting omakase (hojicha roasted to order)',
      menu: [{ i: 'Tea Course (guided multi-infusion)', p: 5950 }, { i: 'Tea & Japanese Sweets', p: 2500 }, { i: 'Chashu — tea-infused liquor', p: 1620 }, { i: 'Gyokuro Martini (bar time)', p: 2200 }],
      sourcing: 'Roasts hojicha to order at the counter; spatial design by Simplicity (Shinichiro Ogata).',
      hook: 'A "tea research lab" by day, an acclaimed tea-cocktail bar by night (50 Best Bars).',
      scale: '10-seat counter, Aoyama — reservation-worthy',
      healthTxt: '🍵 Tokyo · 50 Best Bars', opened: '2014 · Tokyo', threat: 'niche',
      links: [{ kind: 'web', url: 'https://sakurai-tea.jp/en' }, { kind: 'ig', url: 'https://www.instagram.com/sakurai_tea_shop/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Sakurai%20Japanese%20Tea%20Experience%20Aoyama' }] },

    { tier: 'japan', rank: 3, spotlight: 'unique', name: 'Tokyo Saryo', region: 'japan', format: 'Hand-drip sencha cafe', area: 'Sangenjaya, Setagaya, Tokyo', price: 1400, band: 'mid', rating: 3.1, reviews: 42, open: true, ig: 46000,
      sig: 'Hand-drip single-origin sencha — temperature tasting flight',
      menu: [{ i: 'Sencha 2-variety flight + sweet', p: 1400 }, { i: 'Sencha 1-variety + confection', p: 900 }, { i: 'Take-out iced tea', p: 450 }],
      sourcing: 'Single-origin sencha brewed pour-over with their own branded "GREEN DRIPPER".',
      hook: "World's first hand-drip Japanese green-tea cafe — tea served like specialty coffee.",
      scale: 'Minimalist counter, Sangenjaya',
      healthTxt: '🍵 Tokyo · since 2017', opened: '2017 · Tokyo', threat: 'niche',
      links: [{ kind: 'web', url: 'https://www.tokyosaryo.jp/' }, { kind: 'ig', url: 'https://www.instagram.com/senchado_tokyo/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Tokyo%20Saryo%20Sangenjaya' }] },

    { tier: 'japan', rank: 4, spotlight: 'unique', name: 'Suzukien × Nanaya', region: 'japan', format: 'Matcha gelato — 7 intensity levels', area: 'Asakusa, Tokyo (near Sensō-ji)', price: 590, band: 'budget', rating: 3.7, reviews: 1405, open: true, ig: 10200,
      sig: 'No.7 — the "world\'s richest" matcha gelato',
      menu: [{ i: 'Matcha Gelato No.1–6', p: 390 }, { i: 'Matcha Gelato Premium No.7', p: 590 }, { i: 'No.7 double cup', p: 680 }, { i: 'Matcha an-dango (4 types)', p: 500 }],
      sourcing: 'Premium Fujieda (Shizuoka) matcha by Marushichi/Nanaya; 150-yr Asakusa tea house Suzukien.',
      hook: 'The 7-intensity matcha gelato gradient (No.1 → No.7).',
      scale: 'Asakusa flagship + Nanaya e-commerce',
      healthTxt: '🍵 Tokyo · 1,405 reviews', opened: 'Tea house c.1848', threat: 'niche',
      links: [{ kind: 'web', url: 'https://www.suzukien.tokyo/' }, { kind: 'ig', url: 'https://www.instagram.com/suzukien.asakusa/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Suzukien%20Nanaya%20Asakusa' }] },

    { tier: 'japan', rank: 5, spotlight: 'unique', name: 'Restaurant 1899 Ochanomizu', region: 'japan', format: 'Matcha beer garden · "eating tea"', area: 'Ochanomizu, Chiyoda, Tokyo', price: 1500, band: 'premium', rating: 3.5, reviews: 607, open: true, ig: 17500,
      sig: '1899 Matcha Beer (patent-pending green-tea beer) + matcha cuisine',
      menu: [{ i: '1899 Matcha Beer (抹茶ビール)', p: null }, { i: 'Matcha Cheese Seafood Pizza', p: 1500 }, { i: 'Hojicha-infused Spare Ribs', p: 2000 }, { i: 'Matcha Beer Garden course', p: 6000 }],
      sourcing: 'Treats tea as an edible ingredient ("eating tea"); whisks matcha into beer.',
      hook: 'A matcha "beer garden" — tea leaves cooked into ~40 savory dishes.',
      scale: 'Restaurant, Ochanomizu (Ryokan-group "1899" brand)',
      healthTxt: '🍵 Tokyo · matcha beer', opened: '2014 · brand "1899"', threat: 'niche',
      links: [{ kind: 'web', url: 'https://1899.jp/ochanomizu/' }, { kind: 'ig', url: 'https://www.instagram.com/1899_official/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Restaurant%201899%20Ochanomizu' }] },

    { tier: 'japan', rank: 6, spotlight: 'unique', name: 'Kashō-an · Classic Tea & Cocktails', region: 'japan', format: 'Daytime matcha cocktail bar', area: 'Gion Shinbashi, Kyoto', price: 1620, band: 'premium', rating: 4.7, reviews: 62, open: true, ig: null,
      sig: 'Whisked-matcha cocktails (Green Soda, Matcha & Rose)',
      menu: [{ i: 'Green Soda — whisked matcha + soda', p: null }, { i: 'Gosho-guruma — matcha + brandy', p: null }, { i: 'Matcha & Rose', p: null }, { i: 'Retail matcha "Koimaro"', p: 1620 }],
      sourcing: 'Founder whisks usucha matcha fresh per cocktail; matcha is the hero, not the spirit.',
      hook: "Japan's first matcha cocktail bar — open DAYTIME so sunlight shows the green.",
      scale: 'Tiny Gion cocktail bar',
      healthTxt: '🍵 Kyoto · 4.7★', opened: '2021 · Gion', threat: 'niche',
      links: [{ kind: 'web', url: 'https://shop.chanoma.co.jp/special/detail/118' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Classic%20Tea%20and%20Cocktails%20Gion%20Shinbashi' }] },

    { tier: 'japan', rank: 7, spotlight: 'iconic', name: 'Nakamura Tokichi Honten', region: 'japan', format: 'Historic Uji tea house (1854)', area: 'Uji, Kyoto (Uji-bashi-dōri)', price: 1540, band: 'premium', rating: 4.3, reviews: 1624, open: true, ig: 67300,
      sig: 'Namacha Jelly (生茶ゼリイ) + Maruto Parfait',
      menu: [{ i: 'Seasonal Maruto Parfait', p: 1540 }, { i: 'Namacha Jelly cup (takeaway)', p: 520 }, { i: 'Namacha Jelly gift box (6 pcs)', p: 2920 }],
      sourcing: '170-year, 7th-generation Uji tea house; premium Uji matcha.',
      hook: 'Home of the famous "Namacha Jelly" (raw-tea jelly).',
      scale: 'Iconic Uji honten + branches (Ginza, etc.)',
      healthTxt: '🌟 Uji · since 1854', opened: '1854 · Uji', threat: 'niche',
      links: [{ kind: 'web', url: 'https://tokichi.jp/en' }, { kind: 'ig', url: 'https://www.instagram.com/nakamura_tokichi_official/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Nakamura%20Tokichi%20Honten%20Uji' }] },

    { tier: 'japan', rank: 8, spotlight: 'iconic', name: 'Itohkyuemon', region: 'japan', format: 'Uji tea house → matcha sweets', area: 'Uji, Kyoto (Uji honten)', price: 1389, band: 'premium', rating: 4.1, reviews: 202, open: true, ig: 51500,
      sig: 'Itohkyuemon Matcha Parfait + matcha soba',
      menu: [{ i: 'Itohkyuemon Matcha Parfait', p: null }, { i: 'Matcha (green) soba noodles', p: null }, { i: 'Uji Matcha Daifuku (6-pack)', p: 1389 }, { i: 'Uji Matcha Raw Chocolate (16-pc)', p: 1393 }],
      sourcing: '~200-year Uji tea merchant; stone-ground Uji matcha.',
      hook: 'Iconic matcha-parfait powerhouse — even matcha soba & matcha curry.',
      scale: 'Uji honten chabou + branches',
      healthTxt: '🌟 Uji · since 1832', opened: '1832 · Uji', threat: 'niche',
      links: [{ kind: 'web', url: 'https://www.itohkyuemon.co.jp/' }, { kind: 'ig', url: 'https://www.instagram.com/itohkyuemon/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Itohkyuemon%20Uji%20Honten' }] },

    { tier: 'japan', rank: 9, spotlight: 'iconic', name: 'Tsūen Tea (Tsūen Chaya)', region: 'japan', format: "World's oldest tea house (1160)", area: 'Uji, Kyoto (Uji Bridge)', price: 850, band: 'mid', rating: 4.0, reviews: 70, open: true, ig: 3914,
      sig: 'Matcha Parfait + the "Musashi Set"',
      menu: [{ i: 'Matcha Parfait', p: 850 }, { i: 'Matcha Sundae', p: 780 }, { i: 'Uji Kintoki soft serve', p: 600 }, { i: 'Cha (tea) soba', p: 880 }],
      sourcing: 'Traditional Uji tea (matcha/gyokuro/sencha); 24 generations of one family.',
      hook: "Japan's oldest tea house (est. 1160) — the original Uji Bridge tea stop.",
      scale: '860-year-old Uji landmark, 1672 Edo building',
      healthTxt: '🌟 Uji · est. 1160', opened: '1160 · Uji (bldg 1672)', threat: 'niche',
      links: [{ kind: 'web', url: 'https://tsuentea.com/' }, { kind: 'ig', url: 'https://www.instagram.com/tsuen1160/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Tsuen%20Tea%20Uji%20Bridge' }] },

    { tier: 'japan', rank: 10, spotlight: 'iconic', name: 'Gion Komori', region: 'japan', format: 'Matcha & warabi-mochi in an ex-ochaya', area: 'Gion Shinbashi, Kyoto (Shirakawa)', price: 1800, band: 'premium', rating: 4.2, reviews: 97, open: true, ig: null,
      sig: 'Warabi Mochi Parfait (fresh, made to order)',
      menu: [{ i: 'Warabi Mochi Parfait', p: 1800 }, { i: 'Matcha Bavarois Parfait', p: 1700 }, { i: 'Matcha Warabi Mochi', p: 1500 }, { i: 'Komori Anmitsu', p: 1400 }],
      sourcing: 'Kyoto-style matcha + 100% pure warabi-starch mochi, made fresh daily.',
      hook: 'Matcha & warabi-mochi sweets inside a preserved geisha machiya over the Shirakawa.',
      scale: 'Tabelog Hyakumeiten (Top 100) Gion parlour',
      healthTxt: '🌟 Kyoto · Top 100', opened: 'Gion machiya', threat: 'niche',
      links: [{ kind: 'web', url: 'https://www.giwon-komori.com/' }, { kind: 'maps', url: 'https://www.google.com/maps/search/?api=1&query=Gion%20Komori%20Kyoto' }] },
  ],

  // product photos (validated, hotlinkable) — brands not listed fall back to a colour dot
  powderImages: {
    'Ritual Matcha Co.': 'https://ritualmatcha.ph/cdn/shop/files/82C527CD-8412-417F-A044-C8B35484610D-m.jpg?v=1765003806&width=1080',
    'Matcha Moments': 'https://matchamoments.ph/cdn/shop/files/MatchaJar40g.png?v=1774959728&width=1080',
    'Maison Midori': 'https://cdn.shopify.com/s/files/1/0722/4947/5290/files/IMG_0362.jpg?v=1771896071',
    'Yamamasa Koyamaen': 'https://cdn.shopify.com/s/files/1/0670/1930/9219/files/Rebranded_-_Yamamasa.png?v=1777053923',
    'The Matcha Tokyo': 'https://images.tablevibestaticassets.co/52x2a58ziio06i2yg0d6nwlldn2q',
    'Marukyu-Koyamaen': 'https://cdn.shopify.com/s/files/1/0670/1930/9219/files/13.png?v=1777047613',
    'Ippodo': 'https://cdn.shopify.com/s/files/1/0685/8732/3548/files/Gokujo-Hojicha---100g.jpg?v=1754985762',
    'Naoki Matcha': 'https://cdn.shopify.com/s/files/1/0860/9716/6639/files/AMZPL_1_barista-blend-hero-40g.jpg?v=1752807321',
    'Encha': 'https://cdn.shopify.com/s/files/1/0668/5149/files/Latte60g.jpg?v=1766371283',
    'Aiya': 'https://cdn11.bigcommerce.com/s-30z03xaf7j/images/stencil/1280x1280/products/1774/3095/ceremonial-matcha-tin-30g__80403.1781628290.jpg?c=1',
    "Rocky's Matcha": 'https://cdn.shopify.com/s/files/1/0689/8037/5866/files/EDITED100G-29Rocky_sMatchaFeb2024-2-updated.jpg?v=1742012604',
    'Nokori': 'https://cdn.shopify.com/s/files/1/0652/6648/3302/files/komo_foil.png?v=1765275736',
    'Little Retail PH': 'https://littleretailph.com/cdn/shop/products/SHOPEE_LAZPRODUCTS_6_240e11fe-5006-44c0-9eed-3ff636be1bc6.jpg?v=1660878273',
    'Matcha Mill': 'https://matcha-mill.com/cdn/shop/files/30g.jpg?v=1773647805&width=1946',
    'Moonbug Matcha': 'https://moonbugmatcha.com/cdn/shop/files/MOONBUG25-56588-SCANEDIT_1_5bee71fd-75f9-445d-b04f-004557912575.jpg?v=1773227068&width=1946',
    'Made in Matcha': 'https://madeinmatcha.com/cdn/shop/files/IMG_3750.png?v=1760830816&width=1946',
    'Tsujiri': 'https://cdn.shopify.com/s/files/1/0270/3451/7571/files/ume_no_shiro_2048x2048.jpg?v=1597816501',
    'Ito En': 'https://itoen.com/cdn/shop/products/matcha-love-organic.jpg?v=1541692496&width=2048',
    'Jade Leaf': 'https://www.jadeleafmatcha.com/cdn/shop/files/ceremonial-matcha-barista-tin-30g-front_d309535f-9cca-4602-be9c-f7102ff35033.png?v=1763749245&width=1500',
    'Hibiki-an': 'https://www.hibiki-an.com/images/upload/MatchaSupPre_B01.jpg',
    'Nakamura Tokichi': 'https://cdn.shopify.com/s/files/1/0655/4550/2972/files/01_b3f3099f-86e4-4280-a557-96807276f70f.jpg?v=1735027945',
    'Hoshinoen (Yame no Hana)': 'https://cdn.shopify.com/s/files/1/0839/9296/9542/files/tin_2.jpg?v=1779986139',
    'Sobamatsu': '/powders/sobamatsu.jpg', // self-hosted (no durable hotlink — Shopee/Lazada/IG only)
  },

  // brand logos per competitor (self-hosted under /public/competitors/), keyed by exact
  // competitor name — IG/FB profile pic or website mark, render-validated. No entry ⇒ colored numbered circle.
  competitorImages: {
  },
};
